;**********************************************
;** DOWNLOADER **** VER. 1.0 ******************
;**********************************************
;  B: ACCUMULATED CHECKSUM
; R0: DATA POINTER
; R1: DATA BYTE COUNTER
; R2: ID COUNTER
; R3: HOLDS COMMAND
; R4: ERROR COUNTER
; R5: DATA BYTE COUNT
; EADRH/L AND DPTR BOTH HOLD ADDRESS FOR PROGRAMMING AND VERIFICATION

CKJMP	MACRO
	DJNZ	R1,$+5
	LJMP	GETCKSM
	ENDM


CKACC	MACRO
	PUSH	ACC
	ADD	A,B
	MOV	B,A
	POP	ACC
	ENDM

;TEMPORARY DATA STORAGE AREA:
DATABLK	EQU	44H

CSEG
ORG 0E000H
DOWNLOADER:
	CLR	EA	;INTERRUPTS OFF
	SETB	WDWR
	MOV	WDCON,#0	;DISABLE WATCHDOG TIMER
;	MOV	P0,#0FFH
;	MOV	P1,#0FFH
;	MOV	P2,#0FFH
;	MOV	P3,#0FFH
	ANL	CFG841,#1CH
;	MOV	ECON,#0F0H	;SWITCH TO ULOAD MODE
	MOV	SP,#7
        MOV	PSW,#0
        IF (DEBUG=0)
        CLR	RI
        SETB	TI
        ENDIF
CMDRST:
	MOV	ECON,#0FH	;LEAVE ULOAD MODE
	MOV	R2,#0	;ID COUNTER
CMDWAIT:		;WAIT HERE FOR A COMMAND
	MOV	R4,#1	;ERROR COUNTER. SET TO 0 WHEN COMMAND IS RECEIVED
	CALL	RECBYTE
	CJNE	A,#07,ST00
	CALL	RECBYTE
	CJNE	A,#0EH,ST00
	CALL	RECBYTE		;GET # DATA BYTES
	JNZ	ST0
	JMP	GETCKSM		;JMP IF 0 DATA BYTES
ST00:	JMP	IDWAIT
ST0:
	JAGT	25,CMDRST	;JMP IF # DATA BYTES > 25
	MOV	B,A		;B = CHECKSUM
	MOV	R1,A		;R1 = BYTE COUNTER
	MOV	R5,A		;R5 = DATA BYTE COUNT
	CALL	RECBYTE		;GET COMMAND
	CKACC	;ACCUMULATE CHECKSUM
	MOV	R3,A		;SAVE COMMAND
	MOV	R4,#0		;CLEAR ERROR COUNTER
	CKJMP			;JMP IF NO MORE DATA
	;IF WE GET THIS FAR, ADDRESS COMES NEXT
	MOV	R4,#1
	CALL	RECBYTE		;GET ADDRESS HI
	CKACC	;ACCUMULATE CHECKSUM
	CKJMP
	CALL	RECBYTE		;GET ADDRESS MID
	MOV	EADRH,A
	MOV	DPH,A
	CKACC	;ACCUMULATE CHECKSUM
	CKJMP
	CALL	RECBYTE		;GET ADDRESS LO
	MOV	EADRL,A
	MOV	DPL,A
	CKACC	;ACCUMULATE CHECKSUM
	MOV	R4,#0
	CKJMP
	;ANY REMAINING DATA GETS PUT IN DATABLK
	MOV	R0,#DATABLK
SAVEDAT:
	CALL	RECBYTE
	CKACC
	MOV	@R0,A
	INC	R0
	CKJMP
	JMP	SAVEDAT

IDWAIT:
	CJNE	A,#21H,ID2	;FIRST CHAR OF ID COMMAND
	MOV	R2,#3
	JMP	CMDWAIT
ID2:	CJNE	A,#5AH,ID3	;SECOND CHAR OF ID COMMAND
	MOV	A,R2
	CJNE	A,#3,ID5
	DEC	R2		;R2=2
	JMP	CMDWAIT
ID3:	CJNE	A,#0,ID4	;THIRD CHAR OF ID COMMAND
	MOV	A,R2
	CJNE	A,#2,ID5
	DEC	R2		;R2=1
	JMP	CMDWAIT
ID4:	CJNE	A,#0A6H,ID5	;LAST CHAR OF ID COMMAND
	DJNZ	R2,ID5
	CALL	SEND_ID
ID5:
	JMP	CMDRST


GETCKSM:
	CALL	RECBYTE		;CHECKSUM
	MOV	R0,A		;HOLD RCVD CHECKSUM
	MOV	A,R4		;ERROR COUNTER
	JNZ	BADCMD		;JMP IF WE ALREADY ENCOUNTERED ERRORS
	MOV	A,R0
	ADD	A,B            ;RCVD CHECKSUM + ACCUMULATED CKSUM SHOULD = 0
	JZ	CGO
BADCMD:
	MOV	A,#07		;BAD CHECKSUM OR UNRECOGNIZED CMD: SEND NAK AND EXIT
	CALL	SENDBYTE
	JMP	CMDRST
CGO:    ;CHECKSUM OK. CONTINUE WITH COMMAND
	MOV	A,R3		;COMMAND NBR
	CJNE	A,#43H,CG1
	JMP	ERASEPGM
CG1:    CJNE	A,#55H,CG2
	JMP	RRUN
CG2:   	CJNE	A,#57H,CG3
	JMP	PGMBLOCK
CG3:	JMP	BADCMD


ERASEPGM:
	MOV	ECON,#0F0H	;SWITCH TO ULOAD MODE
	MOV	A,R5       	;DATA COUNT
	CJNE	A,#1,VFYBAD	;JMP IF DATA COUNT IS NOT 1
	MOV	ECON,#06H	;ERASE ALL
	;VERIFY ERASURE
	MOV	DPP,#0
	MOV	DPTR,#0
ERVFY:
	CLR	A
	MOVC	A,@A+DPTR
	CJNE	A,#0FFH,VFYBAD
	INC	DPTR
	MOV	A,DPH
	CJNE	A,#0E0H,ERVFY	;STOP WHEN WE GET TO 0E000H
	MOV	A,#06		;ACK
	CALL	SENDBYTE
	JMP	CMDWAIT
VFYBAD:
	MOV	A,#7
	CALL	SENDBYTE
	JMP	CMDRST



PGMBLOCK:
	MOV	ECON,#0F0H	;SWITCH TO ULOAD MODE
	MOV	A,R5		;TOTAL DATA BYTE COUNT
	;SHOULD BE > 4 DATA BYTES FOR PGM CMD:
	JALT	5,PGMBAD
	CLR	C
	SUBB	A,#4		;SUBTRACT COMMAND + ADDRESS SIZE
	MOV	R1,A		;R1 = # BYTES TO PROGRAM
	MOV	R0,#DATABLK
	MOV	DPP,#0
PGMLOOP:
	MOV	A,@R0		;GET A DATA BYTE FROM DATABLK
	MOV	EDATA1,A
	;SKIP PROGRAMMING AND VERIFYING IF CODE ADDRESS >= E000H:
	MOV	A,EADRH
	JALT	0E0H,PGM1
	JMP	PGM2
PGM1:
	MOV	ECON,#82H	;WRITE EDATA1 TO FLASH PROGRAM MEMORY
	;VERIFY THE PROGRAMMING:
	CLR	A
	MOVC	A,@A+DPTR	;BYTE JUST PROGRAMMED
	CJNE	A,EDATA1,NOT_PGMD
PGM2:
	;INCREMENT CODE ADDRESS
	INC	DPTR
	MOV	A,DPH
	MOV	EADRH,A
	MOV	A,DPL
	MOV	EADRL,A
	INC	R0
	DJNZ	R1,PGMLOOP
	MOV	A,#06		;ACK
	CALL	SENDBYTE
	JMP	CMDRST

NOT_PGMD:
	MOV	A,#08		;BYTE NOT PROGRAMMED: SEND NAK AND EXIT
	CALL	SENDBYTE
	JMP	CMDRST
PGMBAD:
	MOV	A,#07		;BAD COMMAND FORMAT: SEND NAK AND EXIT
	CALL	SENDBYTE
	JMP	CMDRST



BADRUN:
	MOV	A,#07
	CALL	SENDBYTE
	JMP	CMDRST

RRUN:
	MOV	A,R5	;TOTAL DATA BYTE COUNT
	CJNE	A,#4,BADRUN	;SHOULD BE 4 DATA BYTES FOR REMOTE RUN
	MOV	DPP,#0
;	MOV	ECON,#0FH	;LEAVE ULOAD MODE
	MOV	A,#06		;ACK
	CALL	SENDBYTE
        JNB     TI,$            ; wait until present char gone
        CLR     TI
        CLR	RI
        MOV	PSW,#0
        MOV	ECON,#0
        MOV	SCON,#0
        MOV	T3CON,#0
        MOV	T3FD,#0
        MOV	T2CON,#0
;        MOV	PLLCON,53H
        MOV	IE,#0
        MOV	PCON,#0

	MOV	R0,#0
CLRA:
	MOV	@R0,#00
	DJNZ	R0,CLRA


;;RESTORE SPECIAL FUNCTION REGISTERS TO RESET STATES:
;	MOV	P0,#0FFH
;	MOV	SP,#07H
;;	MOV	DPL,#0
;;	MOV	DPH,#0
;;	MOV	DPP,#0
;	MOV	PCON,#0

;	MOV	TCON,#0
;	MOV	TMOD,#0
;	MOV	TL0,#0
;	MOV	TL1,#0
;	MOV	TH0,#0
;	MOV	TH1,#0

;	MOV	P1,#0FFH
;	MOV	I2CADD1,7FH
;	MOV	I2CADD2,#7FH
;	MOV	I2CADD3,#7FH

;	MOV	SCON,#0
;	MOV	SBUF,#0
;	MOV	I2CDAT,#0
;	MOV	I2CADD,55H
;	MOV	T3FD,#0
;	MOV	T3CON,#0

;	MOV	P2,#0FFH
;	MOV	TIMECON,#0
;	MOV	HTHSEC,#0
;	MOV	SEC,#0
;	MOV	MIN,#0
;	MOV	HOUR,#0
;	MOV	INTVAL,#0
;	MOV	DPCON,#0

;	MOV	IE,#0
;	MOV	IEIP2,#0A0H
;	MOV	PWMCON,#0

;	MOV	P3,#0FFH
;	MOV	PWM0L,#0
;	MOV	PWM0H,#0
;	MOV	PWM1L,#0
;	MOV	PWM1H,#0
;	MOV	SPH,#0

;	MOV	IP,#0
;	MOV	ECON,#0
;	MOV	EDATA1,#0
;	MOV	EDATA2,#0
;	MOV	EDATA3,#0
;	MOV	EDATA4,#0

;	MOV	EADRL,#0
;	MOV	EADRH,#0

;	MOV	T2CON,#0
;	MOV	RCAP2L,#0
;	MOV	RCAP2H,#0
;	MOV	TL2,#0
;	MOV	TH2,#0

;	MOV	PSW,#0
;	MOV	DMAL,#0
;	MOV	DMAH,#0
;	MOV	DMAP,#9
;	MOV	PLLCON,#53H

;	MOV	ADCCON2,#0
;	MOV	ADCDATAL,#0
;	MOV	ADCDATAH,#0
;	MOV	PSMCON,#0DEH

;	MOV	I2CCON,#0
;	MOV	ADCCON1,#40H

;	MOV	ADCCON3,#0
;	MOV	SPIDAT,#0

;	MOV	SPICON,#4
;	MOV	DAC0L,#0
;	MOV	DAC0H,#0
;	MOV	DAC1L,#0
;	MOV	DAC1H,#0
;	MOV	DACCON,#4


       ;CHIP RESET:
        SETB	WDWR
        MOV	WDCON,#082H
        JMP	$

	CLR	A
	JMP	@A + DPTR

RECBYTE:        ; waits for a single character to be received
                ; by the UART.  places this character into A.
        IF (DEBUG=0)
        JNB     RI,$
        MOV     A,SBUF
        CLR     RI
        ENDIF
        RET

SENDBYTE:       ; sends value contained in A to UART
	IF (DEBUG=0)
        JNB     TI,$            ; wait until present char gone
        CLR     TI              ; must clear TI
        MOV     SBUF,A
        ENDIF
        RET


SEND_ID:
	MOV	DPTR,#ID_STRING
	MOV	R0,#25
SID1:
	CLR	A
	MOVC	A,@A + DPTR
	INC	DPTR
	CALL	SENDBYTE
	DJNZ	R0,SID1
	RET

ID_STRING:	DB 41H,44H,49H,20H,38H,34H,31H,20H,20H,20H,56H,32H,31H,33H,0DH,0AH,78H,88H,0CCH,01H,07H,93H,01H,00H,0AAH



