$MOD841                         ; Use 8052 predefined symbols
;JAN. 26, 2006	CAPACITANCE MEASUREMENT USING AD7747
;FEB. 10, 2006  ADDED INT0 SETTING OF THRESHOLD
;               CHANGED rate COMMAND SO THAT CLKCTRL CAN BE SET
;FEB. 13, 2006	ADDED SECOND CONVERTER. REMOVED FEB. 10 CHANGE.
;FEB. 27, 2006	ADDED COMMAND TO DISPLAY A READING WHEN enter key alone IS PUSHED.
;FEB. 28, 2006	ADDED NOISE MEASUREMENT COMMAND. ADDED "prox 16" COMMAND: THRESHOLD SET TO
;                2X NOISE LEVEL.
;MARCH 2, 2006  ADDING STEP, STEPMODE, AND PHASE commands
;MARCH 6, 2006  added RESTORE command to load steps from flash
;MARCH 7, 2006  added SAVE command
;MARCH 8, 2006  flash read at start-up. phase 0 set at start-up. phase commands from
;               port 0 if stepmode is on. inverted inputs to p0. phase # in p0[4..0].
;               p0.7 is read bit. pullups required.
;               added 'reconfig' command in case flash is bad at start-up.
;MARCH 10,2006  removed "prox" and "select" commands
;MARCH 13, 2006	added threshold type command: 'ttype'. 0: use fast reading, 1: use slow
;                reading, 2: use 2 x peak-to-peak noise reading.
;MARCH 14, 2006 added 'thresh' command: prints current threshold.
;APRIL 21, 2006 serial input of phase.
;               p0.0: clock in, p0.1: data in, p0.2 enable in. p3.5 clock ack out.
;APRIL 25, 2006 changed p0.0, p0.1, and p0.2 to make wiring easier
;               p0.5: clock in, p0.6: data in, p0.7 enable in. p3.5 clock ack out.
;MAY 04, 2006	added 'setp' command. changed serial reading of phase: always active.
;MAY 05, 2006	added 'autoset' command.
;MAY 11, 2006	added 'detect' command.

;AUGUST 14, 2006 "SPI.ASM".  TEST PGM. TESTING MAXIM  MAX6957 LED DRIVER FOR USE IN
;                CAPACITANCE SWITCH CONTROL PANEL.
;AUGUST 16, 2006 testing SPI finished bit (ISPI bit of SPICON). direct test of ISPI
;                (jb ISPI,xxx or jnb ISPI,xxx) does not seem to work.  moving SPICON
;                to register and testing register seems to work.
;SEPT. 05, 2006 NEW PROJECT: SPI_cap_cpanel
;               removed unnecessary variables and code. adding AD7142 code.
;SEPT. 07, 2006 ADDED CODE FOR INITIALIZING FLASH WITH 7142 SETTINGS,TESTING SWITCH PADS,
;               BACKLIGHTING PADS WHEN ACTUATED.
;SEPT. 12, 2006 TURN LEDS ON OR OFF ONLY WHEN THERE IS A CHANGE IN PAD STATUS.
;SEPT. 13, 2006 ABOVE DISABLED. CAPADR, CAPDAT, SPIRX STORED MSB FIRST.
;SEPT. 18, 2006 ADDED SWITCH TYPES
;SEPT. 19, 2006 CONTINUING WITH ABOVE.
;               TYPE DEFINITION: TYPE[4:0] = TYPE NUMBER (0 TO 6 SO FAR),
;                                TYPE[7:5] = GROUP NUMBER FOR RADIO BUTTONS.
;               TYPE	ACTION
;		0	LEDS ON WHEN TOUCHED, OFF WHEN NOT TOUCHED. CAN'T REMOTELY TURN LEDS ON
;		1	0->1 TURNS LEDS ON, 1->0 TURNS LEDS OFF. LEDS CAN BE CONTROLLED REMOTELY.
;		2	0->1 TURNS LEDS OFF. LEDS TURNED ON REMOTELY.
;		3	NO LED ACTION
;		4       0->1 TURNS LEDS ON. LEDS TURNED OFF REMOTELY.
;		5	RADIO BUTTON. TOUCH TURNS ON LEDS, OTHERS IN GROUP OFF. TOUCHED SW LEDS STAY ON WHEN TOUCH REMOVED.
;		6	RADIO BUTTON. LEDS STAY ON ONLY WHEN TOUCHED.
;SEPT. 20, 2006 INITIALIZING ADRS 45H IN AD7142. ADDED LED INTENSITY CONTROL
;SEPT. 21, 2006 COMMANDS ARE NOW EXECUTED WITHIN UART INTERRUPT SERVICE PROC. UART INTERRUPT
;                DISABLED DURING MAIN LOOP SPI STUFF.
;SEPT. 22, 2006 SOFTWARE SPI
;SEPT. 23, 2006 ADDED SECOND AD7142 LOADER (SET_FROM_FLASHX) THAT WRITES EACH REGISTER
;                SEPARATELY. ORIGINAL NOT LOADING.
;SEPT. 24, 2006 ADDED HEX OR DECIMAL IN AND OUT.
;OCT. 04, 2006  SAVING UART RECEIVED CHARS IN BUFFER BEFORE PROCESSING COMMAND.
;OCT. 11, 2006  TEST.  SAVE UART RCVD. CHARS AND COUNT. ADD COMMANDS TO DISPLAY THEM.REMOVED UART TEST
;OCT. 25, 2006  PREPARING FOR BOARD TEST. ADDING JOYSTICK A/D STUFF.
;OCT. 26, 2006  ANALOG TESTING.
;OCT. 27, 2006  ADDED COMMAND TO SET JOYSTICK BASE VALS. TIMER SHOULD SET THEM, BUT NOT WORKING.
;OCT. 30, 2006  ADDING CHANGES TO AVOID REV. F ANOMALIES. (NO PUSH AT START OF SUB, NO HARDWARE SPI)
;OCT. 31, 2006  ADDED JOG BIT TO LED WORD. CHANGED SWITCH AND LED ID BITS.
;NOV. 1, 2006   MORE CHANGES TO L, S, AND Q RESPONSE WORDS. CHANGED RADIO1: 0->1: ON, 1->0: OFF
;NOV. 4, 2006	CORRECTED JOYSTICK SIGN ERROR
;NOV. 8, 2006   CHANGED JOYSTICK SIGNS TO MATCH CORRECTED JOYSTICK MOUNTING.
;               added watchdog timer and watchdog test.
;NOV. 9, 2006   ADDED OPTIONAL DEADBAND AMOUNT TO 'B' COMMAND
;NOV. 14, 2006  ADDED OPTIONAL UART TIMEOUT. IF P2.7 = 0, UART MUST RECEIVE VALID COMMAND
;               WITHIN UART TIMEOUT PERIOD OR BOARD IS RESET.
;NOV. 20, 2006  ADDED 'SAVE' COMMAND. ADDED CHIP RESET TO LOAD CHIP SUB.
;NOV. 21, 2006  USING CHIP INTERRUPT TO SIGNAL SWITCH SCAN COMPLETE. PUT ALL SPI TX/RX
;                WITHIN CRITICAL REGIONS.
;NOV. 22, 2006  VERSION 6.
;NOV. 23, 2006  CHECKING CHIP SCAN COMPLETE BY POLLING P3.2 BIT. USING WORKING STORAGE FOR
;               LED.LED+1 SO THAT TEMPORARY CHANGES ARE NOT RETURNED BY 'L' COMMAND.
;NOV. 24, 2006
;NOV. 27, 2006  SET UART INTERRUPT TO HI PRIORITY. ADDED CRITICAL REGIONS AROUND MULTIPLE
;               BYTE LOAD OR STORE OF STATUS WORDS. ALL INTERRUPTS SET TO SAME LEVEL.
;               WATCHDOG TIMEOUT CHANGED FROM 125 TO 250 MS. WATCHDOG RESET INDICATOR
;               ADDED TO 'S' COMMAND.
;NOV. 28, 2006  EXTERNAL ADC REFERENCE: 5V/2
;NOV. 29, 2006  ADDED 'VERSION' COMMAND
;NOV. 30, 2006  CORRECTED BUG IN FLASH LOAD OF CHIP PARAMS. ADDRESSES 6 AND 7 WERE NOT SAVED.
;DEC. 01, 2006  ADDED A SET CHIP FROM FLASH WITH VERIFICATION SUB.
;DEC. 05, 2006  CHANGED DEFAULT PARAMS FOR CHIP. WAS NOT AUTO CALIBRATING BECAUSE PROXIMITY
;                INDICATION WAS ON MOST OF THE TIME.
;DEC. 06, 2006  CHANGED INITIAL OFFSET LOW VALUES.
;DEC. 07, 2006  ADDED TIMEOUT TO 'SENDCHAR' IN 'UARTIO.ASM'.
;JAN. 11, 2007  MOVED UART TIMEOUT TEST TO A/D INTERRUPT ROUTINE.
;JAN. 30, 2007  FASTER SPI RATE.
;JAN. 31, 2007	ADDING BINARY COMMANDS.
;FEB. 1, 2007	CHANGED ADC SAMPLE TIME FROM 1 TO 5 MS. REMOVED P2.7 UART TIMEOUT OPTION
;FEB. 07, 2007	REMOVED NON-NUMERIC ACK CHARS.
;MAY  26, 2007  COMBINED SPI AND I2C INTERFACE.
;MAY 30,  2007  WORKING VERSION OF I2C INTERFACE ONLY.
;MAY 31,  2007  CHANGED COMMANDS #3 AND #4 FOR I2C. CHANGED AFE OFFSET FOR SWITCH 8 FROM
;                2300H TO 1E00H.
;JUNE 01, 2007  CHANGED POS. AFE OFFSETS FOR ALL SWITCHES.
;JUNE 06, 2007  ADDED FORCED RECAL TO CAP CHIP STARTUP.
;FEB. 06, 2009  IN ASCII MODE, RCVD. CHARS IGNORED IF RXBUF FILLED.
;OCT. 10, 2011  VERSION 01.06H (262). BLINK DRIVES OFF AND TURN OFF ALL OTHER LIGHTS IF THERE IS A COMMUNICATION FAILURE
;                WITH THE CAP CHIP.
;OCT. 11, 2011  BLINK THE CONTINUE LIGHT BEFORE LOADING AND VERIFYING CAP CHIP PARAMETERS FROM FLASH AT STARTUP.
;                CONTINUE LIGHT WILL BLINK AS LONG AS THERE IS A VERIFY FAILURE.
;
;MAY 1, 2012    VERSION 01.07H (263). BREAK OUT OF ABOVE VERIFY LOOP BY PULLING P2.7 LOW (JUMPER JP5 6 & 7)
;MAY 2, 2012    VERSION 01.08H (264). PROGRAM AUTOMATICALLY DETERMINES CAP CHIP TYPE BY READING CHIP ID REGISTER.
;MAY 4, 2012	I2C TYPE IS SLOWER THAN SPI TYPE. THIS CAUSES COMMANDS TO BE LOST OCCASIONALLY. REMOVING CRON AND CROFF FROM I2C
;		 ROUTINES TO ALLOW RECEPTION OF ALL UART CHARS. COMMANDS 3 AND 4 WILL INTERFERE WITH THE NORMAL ACCESS TO THE
;		 CAPACITANCE CHIP. REMOVED COMMUNICATION FAILURE TEST. ADDED COMMAND #17: RETURN CAP CHIP TYPE.
;Nov. 6, 2012   VERSION 01.09H (265)
;FEB. 26, 2013  VERSION 01.0AH (266) ADDED FEEDRATE ADC CHANNEL. ADDED 5TH AXIS CHANNEL.

DEBUG EQU 0
;;SPIF EQU 0

VERMAJ EQU	1
VERMIN EQU	10

MSIZ	EQU	2
CMDSIZ	EQU	20	;size of command buffer
RXBUFSIZ	EQU	20
TICKVAL	EQU	8	;TICK INTERVAL IN MS./5  (40 MS.)
PONWT	EQU	75	;POWER ON WAIT IN TICKS
UCOUNT	EQU	25	;UART TIMEOUT COUNT (TIME = UCOUNT * TICKVAL)

SPI_CLK EQU P3.5
SPI_OUT	EQU	P3.4
SPI_IN	EQU	P3.3
LEDCS1	EQU	P2.5
LEDCS2	EQU	P2.3
CAPCS	EQU	P2.4
DBUG_LED       EQU     P2.1
CLICK	EQU	P2.2
CHIPINT	EQU	P3.2
DOG_RST EQU	P2.0
BINCOM	EQU	P2.6
FINIT	EQU	P2.7

;FOR I2C VERSION OF CAP CHIP (AD7142-1):
SDA		EQU	P3.3
ADD0	EQU	P3.4
ADD1	EQU	P2.4
SCLK	EQU	P3.5

TESTOUT EQU	P3.7


;SHIFT A BYTE LEFT
SHBL	MACRO	BNAM
	MOV	A,BNAM
	RLC	A
	MOV	BNAM,A
	ENDM

;SHIFT A BYTE RIGHT
SHBR	MACRO	BNAM
	MOV	A,BNAM
	RRC	A
	MOV	BNAM,A
	ENDM

;SHIFT BYTE STRING LEFT. CLEAR C BEFORE CALLING.REG IS LEAST SIG BYTE, NBR IS NUMBER OF BYTES.
SBSL	MACRO  REG,	NBR
	SHBL	REG
	IF (NBR > 1)
	 SBSL REG-1,NBR-1
	ENDIF
	ENDM

;SHIFT BYTE STRING RIGHT. CLEAR C BEFORE CALLING.REG IS MOST SIG BYTE, NBR IS NUMBER OF BYTES.
SBSR	MACRO  REG,	NBR
	SHBR	REG
	IF (NBR > 1)
	 SBSR REG+1,NBR-1
	ENDIF
	ENDM

;SHIFT FAC1 MANTISSA LIFT 1 BIT (MULTIPLY BY 2)
FACX2	MACRO   FAC1
	CLR	C
	SBSL	FAC1,MSIZ
	ENDM

;ADD TWO BYTES PLUS CARRY. BYTEA + BYTEB -> BYTEA
PADD	MACRO	BYTEA,BYTEB
	MOV	A,BYTEA
	ADDC	A,BYTEB
	MOV	BYTEA,A
	ENDM

;ADD COMPLEMENT OF BYTE AND CARRY
ADCPL	MACRO	BYTEA
	MOV	A,BYTEA
	CPL	A
	ADDC	A,#0
	MOV	BYTEA,A
	ENDM

;ADD COMPLEMENT OF BYTE AT R1 AND CARRY
ADCPLR1	MACRO
	MOV	A,@R1
	CPL	A
	ADDC	A,#0
	MOV	@R1,A
	DEC	R1
	ENDM

;ADD COMPLEMENT OF BYTE STRING A TO CARRY. RESULT IN BYTE STRING A
;NBR IS NUMBER OF BYTES IN STRING. BSTA IS LEAST SIG. BYTE.
BSCPL	MACRO	BSTA,NBR
	ADCPL	BSTA
	IF (NBR > 1)
	 BSCPL BSTA-1,NBR-1
	ENDIF
	ENDM

;ADD COMPLEMENT OF BYTE STRING @R1 TO CARRY. RESULT IN BYTE STRING @R1
;NBR IS NUMBER OF BYTES IN STRING. @R1 IS LEAST SIG. BYTE.
BSCPLR1	MACRO	NBR
	ADCPLR1
	IF (NBR > 1)
	 BSCPLR1 NBR-1
	ENDIF
	ENDM

;ADD BYTE STRING A TO BYTE STRING B. RESULT IN BYTE STRING A
;NBR IS NUMBER OF BYTES IN STRING. BSTA, BSTB ARE LEAST SIG. BYTES. CLEAR C BEFORE USING
BSADD	MACRO	BSTA,BSTB,NBR
	PADD	BSTA,BSTB
	IF (NBR > 1)
	 BSADD BSTA-1,BSTB-1,NBR-1
	ENDIF
	ENDM

;SHIFT BYTE STRING LEFT. CLEAR C BEFORE CALLING.REGA,REGB IS LEAST SIG BYTE, NBR IS NUMBER OF BYTES.
;REGA IS SHIFTED STRING, REGB RECEIVES RESULT ALSO
SBSLB	MACRO  REGA,REGB,NBR
	SHBL	REGA
	MOV	REGB,A
	IF (NBR > 1)
	 SBSLB REGA-1,REGB-1,NBR-1
	ENDIF
	ENDM

;SHIFT FAC1 MANTISSA LIFT 1 BIT AND PUT IN FAC2.
FACX2B	MACRO   FAC1,FAC2
	CLR	C
	SBSLB	FAC1,FAC2,MSIZ
	ENDM

;ADD FAC2 MANTISSA TO FAC1 MANTISSA
ADDAB	MACRO   FAC1,FAC2
	CLR	C
	BSADD	FAC1,FAC2,MSIZ
	ENDM



;MULTIPLY FAC1 MANTISSA BY 10 (DECIMAL)
; FAC2 IS USED FOR TEMPORARY STORAGE
FACX10	MACRO   FAC1,FAC2
	FACX2B  FAC1,FAC2
	FACX2   FAC1
	FACX2   FAC1
	ADDAB   FAC1,FAC2
	ENDM

;REPLACE VA WITH VA + VB. LEAVE RESULT IN FAC
FADDS	MACRO	VA,VB
	MOV	R0,#VA
	CALL	GETA
	MOV	R0,#VB
	CALL	GETB
	CALL	FADDAB
	MOV	R0,#VA
	CALL SAVEFACR0
	ENDM

;REPLACE VA WITH VA - VB. LEAVE RESULT IN FAC
FSUBS	MACRO	VA,VB
	MOV	R0,#VA
	CALL	GETA
	MOV	R0,#VB
	CALL	GETB
	XRL	FACB,#1
	CALL	FADDAB
	MOV	R0,#VA
	CALL SAVEFACR0
	ENDM

;FAC <- VA + VB.
FADD	MACRO	VA,VB
	MOV	R0,#VA
	CALL	GETA
	MOV	R0,#VB
	CALL	GETB
	CALL	FADDAB
	ENDM

;FAC <- VA - VB.
FSUB	MACRO	VA,VB
	MOV	R0,#VA
	CALL	GETA
	MOV	R0,#VB
	CALL	GETB
	XRL	FACB,#1
	CALL	FADDAB
	ENDM

;FAC <- FAC + VB.
FADDF	MACRO	VB
	MOV	R0,#VB
	CALL	GETB
	CALL	FADDAB
	ENDM

;FAC <- FAC - VB.
FSUBF	MACRO	VB
	MOV	R0,#VB
	CALL	GETB
	XRL	FACB,#1
	CALL	FADDAB
	ENDM

;FAC <- FAC - (DPTR).
FSUBFEX	MACRO
	CALL	GETBEX
	XRL	FACB,#1
	CALL	FADDAB
	ENDM

;SHIFT BYTE @R0 LEFT 4 BITS. SHIFT IN BITS 0-3 OF B
SHL4S	MACRO
	MOV	A,@R0
	SWAP	A
	PUSH	ACC
	ANL	A,#0F0H
	ORL	A,B
	MOV	@R0,A
	POP	ACC
	ANL	A,#0FH
	MOV	B,A
	DEC	R0
	ENDM

;SHIFT BYTE @R0 LEFT 4 BITS. SHIFT IN BITS 0-3 OF B.LAST STEP
SHL4L	MACRO
	MOV	A,@R0
	SWAP	A
	ANL	A,#0F0H
	ORL	A,B
	MOV	@R0,A
	ENDM

;SHIFT MANTISSA LEFT 4 BITS.SHIFT IN B[3..0],R0 POINTS TO LEAST SIG. BYTE.
;NBR IS SIZE OF MANTISSA.
SHLMANT4	MACRO	NBR
	IF	(NBR > 1)
		SHL4S
	ELSE
		SHL4L
	ENDIF
	IF	(NBR >  1)
		SHLMANT4	NBR-1
	ENDIF
	ENDM

;SHIFT MANTISSA AT R0 LEFT 4 BITS. ADRS IS ADDRESS OF MOST SIG BYTE OF MANTISSA.
;A[3..0] IS SHIFTED INTO THE LOW ORDER BYTE.
SHLMANTA	MACRO
	ANL	A,#0FH
	MOV	B,A
	SHLMANT4	MSIZ
	ENDM

;JUMP TO ADRS IF A IS LESS THAN VAL:
JALT	MACRO	VAL,ADRS
	CJNE	A,#VAL,$+5
	SJMP	$+7
	JNC	$+5
	LJMP	ADRS
	ENDM

;JUMP TO ADRS IF A IS GREATER THAN VAL:
JAGT	MACRO	VAL,ADRS
	CJNE	A,#VAL,$+5
	SJMP	$+7
	JC	$+5
	LJMP	ADRS
	ENDM

;MOVE BYTES FROM @R1 TO @R2
FMOV1	MACRO	NBR
	MOV	A,@R1
	MOV	@R0,A
	IF	(NBR > 1)
		INC	R0
		INC	R1
		FMOV1	NBR-1
	ENDIF
	ENDM

;MOVE FLOAT VB TO VA
FMOV	MACRO	VA,VB
	MOV	R0,#VA
	MOV	R1,#VB
	FMOV1	FSIZ
	ENDM

INCEAD	MACRO
	inc	eadrl
	mov	a,eadrl
	jnz	$+4
	inc	eadrh
	ENDM

;SAVE 4 BYTES (1 PAGE) IN FLASH, INCREMENT PAGE ADDRESS:
SAV4	MACRO	NUM1,NUM2
	MOV	EDATA1,#LOW(NUM1)
	MOV	EDATA2,#HIGH(NUM1)
	MOV	EDATA3,#LOW(NUM2)
	MOV	EDATA4,#HIGH(NUM2)
	MOV	ECON,#5
	MOV	ECON,#2
	INCEAD
	ENDM

;GET 4 BYTES FROM FLASH, INCREMENT PAGE ADDRESS:
GET4	MACRO
	MOV	ECON,#1
	INCEAD
	ENDM



;SPI CLOCK HIGH OR LOW TIME = 8 + 3N CYCLES
;12.6 MHZ CLOCK: 2.9 MICROSECS IF N = 10
SPIWAIT	MACRO
;	NOP
;	PUSH	B
;	MOV	B,#1
;	DJNZ	B,$
;	POP	B
	NOP
	PUSH	B       ;OK WITHOUT THE PUSH & POP TOO
	POP	B
	NOP
	ENDM

INCR7R6	MACRO
	INC	R6
	CJNE	R6,#0,$+4
	INC	R7
	ENDM

;CRITICAL REGION ON:
CRON	MACRO
	CLR	EA
	ENDM

;CRITICAL REGION OFF:
CROF	MACRO
	JNB	INTON,$+5
	SETB	EA
	ENDM

;REFRESH WATCHDOG TIMER
REFRESH	MACRO
        CLR     EA              ; refresh watchdog timer
	SETB    WDWR
	SETB    WDE
	SETB    EA
	ENDM

BSEG
ORG 0
numok:		dbit	1
cmdrcvd:	dbit	1
cmderr:		dbit	1


SPIRDY:		DBIT	1
tick:		dbit	1
TPAD:		DBIT	1
cmd_rdy:	dbit	1
usehex:		dbit	1
jog:		dbit	1
jdir:		dbit	1
baseloaded:	dbit	1
JOGOK:		DBIT	1
POWERRDY:	DBIT	1
INTON:		DBIT	1
SPIF:		DBIT	1	;I2C/SPI FLAG
NOCHIP:		DBIT	1	;WILL BE SET IF CAP CHIP WAS NOT IDENTIFIED

DSEG
ORG 30h
cbufptr:	ds	1	;command buffer pointer
cparam:		ds	MSIZ	;command parameter
cparamb:       	ds	MSIZ
display_adr:	ds	MSIZ
tickcount:	ds	1
LEDCS:		DS	1
cptrh:		ds	1
cptrl:		ds	1
PAD:		DS	2	;LAST TOUCH READING
LED:		DS	2	;LED STATUS
LEDT:		DS	2	;WORKING LED STATUS
TYPE:		DS	12	;SWITCH DEFINITIONS
MASK:		DS	2
OFFON:		DS	2
ONOFF:		DS	2
LEDI:		DS	1	;LED CURRENT (0 TO 15)
WRD:		DS	2
rxptr:		ds	1
dband:		ds	2	;joystick deadband
basecount:	ds	1
JOGH:		ds	2
PONCOUNT:	DS	1	;POWER ON COUNT
UTMOUT:		DS	1	;UART TIMEOUT COUNTER
LEDCON:		DS	2
LEDCOF:		DS	2
CMDNBR:		DS	1
BYTECOUNT:	DS	1

ISEG
ORG 080h
cmdbuf:		ds	20      ;command buffer
outbuf:		ds	10
rxbuf:		ds	RXBUFSIZ


xj:		ds	2	;x joystick reading
yj:		ds	2
wj:		ds	2
zj:		ds	2
tj:		ds	2	;5th axis
		ds	4	;unused chans
fr:		ds	2	;feedrate pot rdg.
xb:		ds	2	;x base
yb:		ds	2
wb:		ds	2
zb:		ds	2
tb:		ds	2

stack:

XSEG
ORG 100h
;stepbase:	ds	MAXSTEPS*STEPSIZE


;____________________________________________________________________
                                                  ; BEGINNING OF CODE
CSEG

ORG 0000h

        JMP     MAIN

;____________________________________________________________________
                                             ; INTERRUPT VECTOR SPACE

ORG 0003h	;EXTERNAL INT. 0       	PRIORITY 2
		RETI
ORG 000BH	;TIMER/COUNTER 0  	PRIORITY 4
		RETI
ORG 0013H	;EXTERNAL INT. 1	PRIORITY 5
		RETI
ORG 001BH	;TIMER/COUNTER 1	PRIORITY 6 bn
		RETI
ORG 0023H	;UART RI + TI		PRIORITY 8
		jmp 	UARTINT
ORG 002BH	;TIMER/COUNTER 2	PRIORITY 9
		RETI
ORG 0033h	; ADC ISR               PRIORITY 3
                jmp	adcint
ORG 003BH	;SPI/IIC       		PRIORITY 7
		RETI
ORG 0043H	;PSMI	       		PRIORITY 1 (HIGHEST)
		RETI
ORG 0053H	;TII	       		PRIORITY 11 (LOWEST)
		RETI
ORG 005BH	;WATCHDOG      		PRIORITY 2
		RETI


adcint:
	nop
	push	acc
	push	psw
	mov	psw,#018h	;select register bank 3
;	CLR	EA
	MOV	R2,ADCDATAH
	MOV	R3,ADCDATAL
;	SETB	EA
	mov	a,R2
	swap	a
	anl	a,#07h		;a = chan #
	rl	a		;2 bytes/rdg
	add	a,#xj
	mov	r0,a
	mov	a,R2
	anl	a,#0fh		;remove id bits
	mov	@r0,a
	inc	r0
	MOV	A,R3 
	mov	@r0,A
	; toggle pin 25 to view timing on scope
	CPL	TESTOUT

	;SELECT NEXT CHANNEL:
	INC	ADCCON2
	ANL	ADCCON2,#07H
	jb	baseloaded,adiret
        djnz	basecount,adiret
        call	setbase
adiret:
	djnz	tickcount,adifin
	setb	tick			;40 ms have elapsed
	mov	tickcount,#TICKVAL
	;TICK INTERVAL HAS ELAPSED
	;UART TIMEOUT TEST
;	JB	P2.7,NUT
;    	DJNZ	UTMOUT,NUT
;    	CLR	EA
;	SETB	WDWR
;	MOV	WDCON,#82H	;IMMEDIATE RESET
;	JMP	$
NUT:
	JB	POWERRDY,ADIFIN
	DJNZ	PONCOUNT,ADIFIN
	SETB	POWERRDY		;POWER ON DELAY OVER
adifin:
	pop	psw
	pop	acc
	reti


;UART interrupt - characters are received here...
UARTINT:
	jnb	ri,uartend	;jump if not RI (receive interrupt) bit set. (ignore tx interrupt)
	PUSH	B		; push register B (Multiplication register)
	push	acc		; push accumulator
	push	psw		; push program status word
	mov	psw,#010h	;select register bank 2
	
; character received gets us here,
; or receive interrupt active when we get to the end of this stuff...
UA:
	mov	a,sbuf  	; move serial buffer (SBUF) to accumulator (a, or acc).
	clr	ri          ;clear rcv interrupt flag
	JNB	BINCOM,ASCC	;JMP IF ASCII COMMUNICATIONS
	;BINARY COMMUNICATIONS
	CALL	BINCHECK
	JMP	UFIN
	
; ASCII COMMUNICATIONS - DEPRECATED
	;save character in buffer
ASCC:	JZ	UFIN		;IGNORE NULL
	cjne	a,#0ah,savchr
	jmp	ufin		;ignore line feed
savchr:
	mov	r0,rxptr
	mov	@r0,a		;save char
	cjne	r0,#rxbuf+RXBUFSIZ-1,$+3
	jnc	bfull           ;jmp if buffer full
	inc	rxptr		;increment buffer pointer
bfull:
	cjne	a,#0dh,ufin	;jmp if not cr
	call	process_buf	;char is cr: execute the command
ufin:	JB	ri,UA		;JMP IF ANOTHER CHAR HAS BEEN RECEIVED
	pop	psw
	pop	acc
	POP	B
uartend:
	reti

; BINARY COMMANDS (NORMAL MODE) LAND HERE
; most recent rx char in A
BINCHECK:
	CJNE	A,#0FFH,BIN1	;JMP IF NOT RUBOUT
SYNC:	MOV	BYTECOUNT,#0
	JMP	BINFIN
	
; not rubout, so maybe command or params...
; If bit 7 is set, this is the first character of a command,
; which is the command number.  If so, store the command number and
; jump to finish - wait for next characters which complete the command.
BIN1:
	;first byte of command? (bit 7 set only on commands)
	JNB	ACC.7,BDAT	; jump if not the command byte.

	; fall through to here if bit 7 is set - this is a command.
	
	; store the command number
	MOV	CMDNBR,A
	
	; set the byte count to 1
	MOV	BYTECOUNT,#1
	
	; be done for now, wait for next byte.
	JMP	BINFIN

	
	; bit 7 was not set, this is parameters for the command.
	; Increment the byte counter.
BDAT:
	;ASSUME BYTE IS DATA OR CHECKSUM
	PUSH	ACC		;push received char.
	MOV	A,BYTECOUNT	; load bytecount into accumulator. (should be 1 here, could be 0)
	INC	BYTECOUNT	; increments byte count to 2 or higher for commands
	JNZ	BIN2		; jump if Accumulator is not zero
	; accumulator was zero - ERROR: NO COMMAND WAS RECEIVED
	POP	ACC
	JMP	SYNC


	; A holds incremented byte count (1 or 2 or more) here
	; when it holds 1, we got a rubout and are resetting.
	; normally, should hold 2 or more when receiveing commands.
	; MSB of data
BIN2:

	DEC	A			; decrement byte count back
	JNZ	BIN3		; if more than zero, go to next byte...
	
	; first data byte received.
	;MSB DATA RCVD
	POP	ACC
	MOV	CPARAM,A	; store command parameter byte 1
	JMP	BINFIN
	
	; checking for second data byte
BIN3:
	DEC	A
	JNZ	BIN4		; if more than zero, check for next byte
	
	; second data byte received
	;LSB DATA RCVD
	POP	ACC
	MOV	CPARAM+1,A	; store command parameter byte 2
	JMP	BINFIN
	
	
BIN4:
	DEC	A
	JNZ	BIN5		; if not zero here, we have too many chars in the command.
	
	; checksum byte now.
	;CHECKSUM RCVD
	; pop restores checksum char to ACC
	POP	ACC
	
	; now add back the last 3 characters that form the command.
	ADD	A,CMDNBR
	ADD	A,CPARAM
	ADD	A,CPARAM+1
	
	; now logical and with 0x7F
	ANL	A,#07FH
	
	; this should leave us with 0 for good checksums.
	JNZ	SYNC	;JMP IF CHECKSUM ERROR
	
	; fall to here with good command.
	; CMDNBR contains command byte (including makeup bits for param bytes).
	; CPARAM, CPARAM + 1 contain the parameters
	;BINARY COMMAND HAS BEEN RECEIVED
	MOV	A,CMDNBR
	
	; if bit 6 not on, jump to MUP1.
	JNB	ACC.6,MUP1
	
	; bit 6 was on, put the makeup bit back on the first param byte.
	ORL	CPARAM,#80H 	;ADD MAKEUP BIT
	
	; if bit 5 is on, add makeup bit back on the second param byte.
MUP1:
	JNB	ACC.5,MUP2
	ORL	CPARAM+1,#80H 	;ADD MAKEUP BIT
	
	; A holds the command number with makeup bits and command bit.
	; strip off the high 3 bits (command, makup 1, makeup 2);
MUP2:
	; logical and to strip upper 3 bits, leaving command number.
	ANL	A,#1FH	;A = COMMAND NUMBER
	
	; rotate left by 1 bit.
	RL	A		;A = OFFSET INTO JMPTBL
	;EXECUTE COMMAND:
	CPL	DBUG_LED
	setb	numok
	CALL	EXBIN
;if a = 0: bad command. a = 1: good command a = 2: good command, no ack
	jnz	bpcb
	mov	A,#'0'          ;BAD
	CPL	CLICK
	jmp	bpcp
bpcb:	cjne	a,#2,bpcg
    	jmp	bpcig
b pcg:	MOV     A,#'1'          ;GOOD
	MOV	UTMOUT,#UCOUNT	;RESET UART TIMEOUT COUNT
bpcp:
	CALL    SENDCHAR
	MOV	DPTR,#SEPARATOR
	CALL	SENDSTRING
bpcig:	call	cmd_init
	JMP	BINFIN
BIN5:
	;ERROR: TOO MANY CHARS
	POP	ACC
	JMP	SYNC
BINFIN:
	RET

	; A contains the command number, shifted 1 bit left.
	; create the address of the command function using
	; the address of the jump table, and the shifted command number.
EXBIN:
	mov	r0,a
	mov	dptr,#jmptbl
	movc	a,@a+dptr       ;high byte of addrs
	mov	r1,a
	mov	a,r0
	inc	a
	movc	a,@a+dptr       ;low byte of address
	mov	dpl,a
	mov	dph,r1
	clr	a
	jmp	@a+dptr		;jump to command procedure
	RET			;WE SHOULD NEVER GET HERE

PAWS:
	MOV	R2,#0
PAWS2:	MOV	R3,#0
PAWS3:	LJMP	$+3
	LJMP	$+3
	LJMP	$+3
	LJMP	$+3
	;add these for 842:
	LJMP	$+3
	LJMP	$+3
	LJMP	$+3

	DJNZ	R3,PAWS3
        REFRESH              ; refresh watchdog timer
	DJNZ	R2,PAWS2
	RET
;*****************************************************************************************
MAIN:                                                                                  ; *
;*****************************************************************************************
	CLR	DOG_RST
	JNB	WDS,MN1
	SETB	DOG_RST	;SET TO INDICATE WATCHDOG TIMEOUT
MN1:
	IF(DEBUG = 0)
	;ENABLE WATCHDOG TIMER:
	SETB	WDWR
	MOV	WDCON,#42h	;250 MS TIME-OUT
	ENDIF
	mov	p0,#0ffh	;set up port 0 for inputs
	SETB	CHIPINT		;INPUT.  CHIP INTERRUPT
	CLR	INTON
	SETB	FINIT		;INPUT.  0 = INITIAL FLASH LOAD
	SETB	BINCOM		;INPUT. 0 = ASCII, 1 = BINARY COMMUNICATIONS
	MOV	BYTECOUNT,#0	;INITIALIZE BINARY COM.
	MOV	UTMOUT,#UCOUNT	;UART TIMEOUT
	MOV	IP,#0H		;SET ALL INTERRUPTS TO LO.
	MOV	PSW,#00H	;SELECT REGISTER BANK 0
;	IF(DEBUG = 0)
        MOV     SP,#stack-1
;        ENDIF
        clr	usehex
        mov	dband,#00h
        mov	dband+1,#32h	;dband = 50
        mov	basecount,#200
        clr	baseloaded
        CLR	JOGOK
        MOV	PONCOUNT,#PONWT
        CLR	POWERRDY
        mov	tickcount,#TICKVAL
        clr	tick
        MOV	R0,#XB
        MOV	R1,#8
        CLR	A
CB0:    MOV	@R0,A
        INC	R0
        DJNZ	R1,CB0

        orl	cfg841,#081h	;enable internal xram,extended stack pointer
        MOV	PLLCON,#01H     ;max rate for 3 volt part: xtal/2
       ; MOV	PLLCON,#02H     ;slow it down more for 842 TEST
        setb	p3.3		;input miso
        IF(DEBUG = 0)
	; CONFIGURE UART....
        ;38400:
        MOV     T3CON,#083h	;Will need to disable UART configuration
        MOV     T3FD,#8		;when using debugger as any writes to UART

	MOV	T3FD,#2Dh	; for 38400 using 842 with 32.768khz crystal

        MOV     SCON,#52h       ;timing or config registers could affect
                                ;the debugger interface


;;** mode 3 UART, timer 1 baud rate gen.
;	mov	pcon,#080h	;smod = 1
;	mov	tmod,#020h	;autoload timer 1
;	mov	th1,#242	;rate = 37449: -2.5% error
;	clr	rclk   		;use timer1 for rx
;	clr	tclk		;use tmr1 for tx
;	mov	scon,#0dah	;mode 3, data bit 8 = 1
;	setb	tr1		;start timer 1
;**

	ENDIF
	;A/D SETUP:
;	MOV	ADCCON1,#0BEH	;ENABLE ADC, INTERNAL REF, DIV RATIO 2,S/H TIME 4,T2 TRIGGER
	MOV	ADCCON1,#0FEH	;ENABLE ADC, EXTERNAL REF, DIV RATIO 2,S/H TIME 4,T2 TRIGGER
	MOV	ADCCON2,#0	;CHAN 0
;	MOV	RCAP2H,#0eah	;1 ms sample time
;	MOV	RCAP2L,#066h
	MOV	RCAP2H,#094h	;5 ms sample time

	MOV	RCAP2H,#063h	;5 MS ON 842 CHIP WITH 32.768khz crystal
	MOV	RCAP2H,#0a3h	;5 MS ON 842 CHIP WITH 32.768khz crystal

	MOV	RCAP2L,#00h
	MOV	T2CON,#04H      ;START TIMER 2

	;initialize command decoder
	push	psw
	mov	psw,#010h	;select register bank 2 (used exclusively by UART)
	call	cmd_init
	pop	psw
; CONFIGURE SPI
	MOV	SPICON,#0    	;disable SPI hardware
	SETB	LEDCS1		;CHIP SELECTS
	SETB	LEDCS2
	SETB	CAPCS
	SETB	SPI_CLK
	SETB	SPI_IN      	;bit is an input
        MOV	LEDI,#15	;LED CURRENT 0: 1/16, 15: 16/16
	MOV	LEDCS,#0
        CALL	LED_CONFIG
        INC	LEDCS
        CALL	LED_CONFIG

	;I2C STOP:
	CLR	SDA
	SETB	SCLK
	SETB	ADD0
	SETB	ADD1
	CALL	IDLY
	SETB	SDA
	CALL	IDLY

	; DETERMINE CHIP TYPE:
	MOV	B,#5	;# TIMES TO TRY
FINDCHIP:
	PUSH	B
	CLR	NOCHIP
	CLR	SPIF	;IIC CHIP?
	MOV	R7,#0
	MOV	R6,#17H		;CAP CHIP ID REGISTER
	CALL	CAP_RCV
	CJNE	R5,#0E6H,CDES	;JMP IF NOT EXPECTED VAL
	;SO FAR SO GOOD
	MOV 	A,R4	;LOW ORDER ID
	ANL	A,#0F0H
	CJNE	A,#20H,CDES
	;CHIP IS IIC
	POP	B		;CLEAR STACK
	JMP	CDE
CDES:
	SETB	SPIF	;SPI CHIP?
	MOV	R7,#0
	MOV	R6,#17H		;CAP CHIP ID REGISTER
	CALL	CAP_RCV
	CJNE	R5,#0E6H,CDUKN	;JMP IF NOT EXPECTED VAL
	;SO FAR SO GOOD
	MOV 	A,R4	;LOW ORDER ID
	ANL	A,#0F0H
	CJNE	A,#20H,CDUKN
	;CHIP IS SPI
	POP	B		;CLEAR STACK
	JMP	CDE
CDUKN:
	POP	B
	DJNZ	B,FINDCHIP

	SETB	NOCHIP	;CHIP NOT IDENTIFIED
CDE:
	JNB	FINIT,CDE1
	jmp	CFG0            ;JMP IF NO INITIAL FLASH LOAD
CDE1:
        call	iload		;LOAD FLASH WITH DEFAULT PARAMS
TST1:
	SETB	C
	CALL	STG0
	CALL	PAWS
	CLR	C
	CALL	STG0
	SETB	C
	CALL	STG1
	CALL	PAWS
	CLR	C
	CALL	STG1
	SETB	C
	CALL	STG2
	CALL	PAWS
	CLR	C
	CALL	STG2
	SETB	C
	CALL	STG3
	CALL	PAWS
	CLR	C
	CALL	STG3
	SETB	C
	CALL	STG4
	CALL	PAWS
	CLR	C
	CALL	STG4
	SETB	C
	CALL	STG5
	CALL	PAWS
	CLR	C
	CALL	STG5
	SETB	C
	CALL	STG6
	CALL	PAWS
	CLR	C
	CALL	STG6
	SETB	C
	CALL	STG7
	CALL	PAWS
	CLR	C
	CALL	STG7
	SETB	C
	CALL	STG8
	CALL	PAWS
	CLR	C
	CALL	STG8
	SETB	C
	CALL	STG9
	CALL	PAWS
	CLR	C
	CALL	STG9
	SETB	C
	CALL	STG10
	CALL	PAWS
	CLR	C
	CALL	STG10
	SETB	C
	CALL	STG11
	CALL	PAWS
	CLR	C
	CALL	STG11

	;Send UART test string:
	call uart_test

        JMP	TST1
CFG0:
	JNB	FINIT,BREAK	;BREAK OUT OF THIS LOOP IF FINIT LOW (JP5 PIN 6)
	SETB	C
	CALL	STG0
	CALL	PAWS
	CLR	C
	CALL	STG0
	CALL	PAWS
	CALL	SET_FROM_FLASH
        CALL	VERIFY
        JZ	CFG0
BREAK:

        CALL	CAPSTART
;	CALL	SET_FROM_FLASHV	;TO BE TESTED
;;        MOV	LEDI,#15	;LED CURRENT 0: 1/16, 15: 16/16
;;	MOV	LEDCS,#0
;;        CALL	LED_CONFIG
;;        INC	LEDCS
;;        CALL	LED_CONFIG
        ;CLEAR SWITCH STATUS
        MOV	PAD,#0
        MOV	PAD+1,#0
        ;CLEAR LED STATUS BITS:
        MOV	LED,#0
        MOV	LED+1,#0
        MOV	LEDT,#0
        MOV	LEDT+1,#0
        MOV	LEDCON,#0
        MOV	LEDCON+1,#0
        MOV	LEDCOF,#0FFH
        MOV	LEDCOF+1,#0FFH
        ;SET UP SWITCH TYPES
        MOV	TYPE+11,#25H	;STAGE 11: RADIO GROUP 1        DRIVES ON
        MOV	TYPE+10,#01H	;STAGE 10: 0->1 ON, 1->0 OFF    AUX
        MOV	TYPE+9,#06H	;STAGE 9: RADIO1 GROUP 0        TS UP
        MOV	TYPE+8,#25H	;STAGE 8: RADIO GROUP 1         DRIVES OFF
        MOV	TYPE+7,#02H	;STAGE 7: 0->1 LED OFF          JOG ENBL
        MOV	TYPE+6,#06H	;STAGE 6: RADIO1 GROUP 0        TS DOWN
        MOV	TYPE+5,#01H	;STAGE 5: 0->1 ON, 1->0 OFF     RAPID
        MOV	TYPE+4,#45H	;STAGE 4: RADIO GROUP 2         SPEED 1
        MOV	TYPE+3,#45H	;STAGE 3: RADIO GROUP 2         SPEED 2
        MOV	TYPE+2,#45H	;STAGE 2: RADIO GROUP 2 	SPEED 3
        MOV	TYPE+1,#45H	;STAGE 1: RADIO GROUP 2		SPEED 4
        MOV	TYPE,#02H	;STAGE 0: 0->1 LED OFF		CONTINUE

	;WATCHDOG RESET INDICATION:
	JNB	DOG_RST,WW0     ;JMP IF EXTERNAL RESET
	;INTERNAL RESET
    	ORL	LEDT+1,#10H	;TURN ON "SPEED 1" LIGHT
    	JMP	WW1
WW0:    ;EXTERNAL RESET
        ORL	LEDT+1,#2	;TURN ON "SPEED 4" LIGHT
WW1:
	IF(DEBUG = 0)
	SETB	ES		;enable UART interrupt
	ENDIF
	SETB	EADC		;ENABLE ADC INTERRUPT
	SETB	INTON
	SETB    EA      	;global interrupt enable
WAIT:
        REFRESH              ; refresh watchdog timer
;	CPL	DBUG_LED
;	;UART TIMEOUT TEST
;	JB	P2.7,NUT
;    	DJNZ	UTMOUT,NUT
;    	CLR	EA
;	SETB	WDWR
;	MOV	WDCON,#82H	;IMMEDIATE RESET
;	JMP	$
;NUT:
	;READ JOYSTICKS HERE
	mov	jogh,#0
	mov	a,#0    ;FIRST CHAN: X
	call	jscheck
	mov	a,jogh+1
	mov	c,jog
	mov	acc.0,c
	mov	c,jdir
	mov	acc.1,c
	mov	jogh+1,a
	mov	a,#1    ;SECOND CHANNEL: Y
	call	jscheck
	mov	a,jogh+1
	mov	c,jog
	mov	acc.2,c
	mov	c,jdir
	mov	acc.3,c
	mov	jogh+1,a
	mov	a,#2    ;THIRD CHANNEL: W
	call	jscheck
	mov	a,jogh+1
	mov	c,jog
	mov	acc.6,c
	mov	c,jdir
	mov	acc.7,c
	mov	jogh+1,a
	mov	a,#3    ;FOURTH CHANNEL: Z
	call	jscheck
	mov	a,jogh+1
	mov	c,jog
	mov	acc.4,c
	mov	c,jdir
	mov	acc.5,c
	mov	jogh+1,a
	;SET JOGOK IF A JOG IS REQUESTED AND POWER SWITCH IS ON:
	MOV	A,LED
	JNB	ACC.3,NOJOG	;JMP IF POWER SW. OFF
	JNB	POWERRDY,NOJOG1
	MOV	A,JOGH+1
	ANL	A,#55H
	JZ	NOJOG1
	SETB	JOGOK
	JMP	NJS
NOJOG:  MOV	PONCOUNT,#PONWT		;SET POWER ON DELAY
	CLR	POWERRDY
NOJOG1:	CLR	JOGOK
NJS:
	JB	CHIPINT,WAIT       ;JMP IF INTERRUPT BIT IS HIGH.
	;clear chip interrupt signal by reading register:
	;signal should clear after address is received.
RSTCI:	MOV	R7,#0       ;MSB
	MOV	R6,#0AH
	CALL	CAP_RCV         ;LOOK AT CONVERSION INTERRUPT REGISTER
	JNB	CHIPINT,RSTCI	;IF INTERRUPT SIG. IS STILL ACTIVE, TRY AGAIN.
	;VERIFY THAT STAGE 1 COMPLETE BIT IS SET:
	MOV	A,R4
	JB	ACC.0,RLLR
	JMP	WAIT
RLLR:
	MOV	R7,#0
	MOV	R6,#08H
	CALL	CAP_RCV         ;LOOK AT LOW LIMIT REGISTER
	;R5.R4 = TOUCH READING
	;HI ORDER 4 BITS SHOULD BE ZERO:
	MOV	A,R5
	ANL	A,#0F0H
	JNZ	RLLR
	;LOOK FOR OFF-TO-ON CHANGE OF STATE:
	MOV	A,PAD           ;LAST READING
	XRL	A,R5	        ;1 = CHANGE OF STATE
	MOV	R2,A
	ANL	A,R5            ;1 = OFF->ON
	MOV	OFFON,A
	MOV	A,PAD+1         ;LAST READING
	XRL	A,R4            ;1 = CHANGE OF STATE
	MOV	R3,A
	ANL	A,R4            ;1 = OFF->ON
	MOV	OFFON+1,A
	;R2.R3 = CHANGE OF STATE
	MOV	A,R5
	CPL	A
	ANL	A,R2
	MOV	ONOFF,A
	MOV	A,R4
	CPL	A
	ANL	A,R3
	MOV	ONOFF+1,A
	MOV	PAD,R5
	MOV	PAD+1,R4
	;SCAN SWITCHES FOR CHANGES:
	MOV	R0,#TYPE
	MOV	MASK,#0         ;BIT SELECTION MASK HI
	MOV	MASK+1,#1       ;BIT SELECTION MASK LO
SWSCAN0:
	MOV	A,@R0		;SWITCH TYPE
	ANL	A,#1FH		;REMOVE GROUP #
	JNZ	SWSCAN1
	;TYPE 0: LED FOLLOWS TOUCH
	MOV	A,MASK
	CPL	A
	ANL	LEDT,A
	CPL	A
	ANL	A,PAD		;ISOLATE SWITCH BIT
	ORL	LEDT,A		;PUT INTO LED BIT
	MOV	A,MASK+1
	CPL	A
	ANL    	LEDT+1,A
	CPL	A
	ANL	A,PAD+1
	ORL	LEDT+1,A
	JMP	NEXTPAD

SWSCAN1:
	DEC	A
	JNZ	SWSCAN2
	;TYPE 1: 0->1 TURNS LED ON, 1->0 TURNS LED OFF
	MOV	A,OFFON
	ANL	A,MASK          ;GET OFF->ON BIT
	ORL	LEDT,A		;PUT IT INTO LED
	MOV	A,OFFON+1
	ANL	A,MASK+1
	ORL	LEDT+1,A

	MOV	A,ONOFF
	ANL	A,MASK
	CPL	A
	ANL	LEDT,A
	MOV	A,ONOFF+1
	ANL	A,MASK+1
	CPL	A
	ANL	LEDT+1,A
	JMP	NEXTPAD

SWSCAN2:
	DEC	A
	JNZ	SWSCAN3
	;TYPE 2: 0->1 TURNS LED OFF
	MOV	A,OFFON
	ANL	A,MASK
	CPL	A
	ANL	LEDT,A
	MOV	A,OFFON+1
	ANL	A,MASK+1
	CPL	A
	ANL	LEDT+1,A
	JMP	NEXTPAD

SWSCAN3:
	DEC	A
	JNZ	SWSCAN4
	;TYPE 3: DO NOTHING
	JMP	NEXTPAD

SWSCAN4:
	DEC	A
	JNZ	SWSCAN5
	;TYPE 4: 0->1 TURNS LED ON
	MOV	A,OFFON
	ANL	A,MASK          ;GET OFF->ON BIT
	ORL	LEDT,A		;PUT IT INTO LED
	MOV	A,OFFON+1
	ANL	A,MASK+1
	ORL	LEDT+1,A
	JMP	NEXTPAD

SWSCAN5:
	DEC	A
	JNZ	SWSCAN6
	;TYPE 5: RADIO BUTTON
	MOV	A,MASK
	ANL	A,OFFON		;ISOLATE BIT FOR THIS SWITCH
	JZ	RADIO1		;JMP IF SWITCH IS NOT TOUCHED
	;SWITCH IS TOUCHED
	CALL	GPOFF		;TURN OFF LEDS IN GROUP
	ORL	LEDT,A		;PUT BIT INTO LED
	JMP	NEXTPAD
RADIO1:
	MOV	A,MASK+1
	ANL	A,OFFON+1
	JZ	NEXTPAD
	CALL	GPOFF
	ORL	LEDT+1,A
	JMP	NEXTPAD

SWSCAN6:
	;ASSUME TYPE 6: RADIO1 BUTTON. ON ONLY WHEN TOUCHED
	;LOOK AT HI BYTE
	MOV	A,MASK
	ANL	A,OFFON		;ISOLATE BIT FOR THIS SWITCH
	JZ	RADIO2		;JMP IF SWITCH IS NOT TOUCHED
	;SWITCH IS TOUCHED
	CALL	GPOFF		;TURN OFF LEDS IN GROUP
	ORL	LEDT,A		;PUT BIT INTO LED
	JMP	RADIO3
RADIO2:
	;LOOK AT LO BYTE
	MOV	A,MASK+1
	ANL	A,OFFON+1
	JZ	RADIO3
	CALL	GPOFF
	ORL	LEDT+1,A
RADIO3:	;SWITCH IS NOT TOUCHED
	MOV	A,ONOFF
	ANL	A,MASK
	CPL	A
	ANL	LEDT,A
	MOV	A,ONOFF+1
	ANL	A,MASK+1
	CPL	A
	ANL	LEDT+1,A
;;	JMP	NEXTPAD

NEXTPAD:
	INC	R0      ;POINT TO NEXT SWITCH
	;SHIFT MASK BIT LEFT 1:
	CLR	C
	MOV	A,MASK+1
	RLC	A
	MOV	MASK+1,A
	MOV	A,MASK
	RLC	A
	MOV	MASK,A
	JB	ACC.4,SCANOVR
	JMP	SWSCAN0
SCANOVR:
        MOV	A,LEDT+1	;LED STATUS LO
        CRON
        ANL	A,LEDCOF+1   	;REMOVE BITS COMMANDED OFF
        ORL	A,LEDCON+1 	;ADD BITS COMMANDED HIGH
        MOV	LEDCON+1,#0
        MOV	LEDCOF+1,#0FFH
        CROF
        MOV	LEDT+1,A
	RRC	A
	CALL	STG0
	RRC	A
	CALL	STG1
	RRC	A
	CALL	STG2
	RRC	A
	CALL	STG3
	RRC	A
	CALL	STG4
	RRC	A
	CALL	STG5
	RRC	A
	CALL	STG6
	RRC	A
	CALL	STG7
	MOV	A,LEDT ;MSB
	CRON
        ANL	A,LEDCOF
        ORL	A,LEDCON
        MOV	LEDCON,#0
        MOV	LEDCOF,#0FFH
        CROF
        MOV	LEDT,A
	RRC	A
	CALL	STG8
	RRC	A
	CALL	STG9
	RRC	A
	CALL	STG10
	RRC	A
	CALL	STG11
	CRON
	MOV	LED,LEDT
	MOV	LED+1,LEDT+1
	CROF
;	;TEST CAP CHIP BY READING ITS ID:
;	mov	R6,#17H
;	mov	R7,#0
;	CALL	CAP_RCV
;	;RESULT IN R5.R4
;	CJNE R5,#0E6H,COMFAIL  ;R5 SHOULD = E6
;	MOV	A,#0F0H
;	ANL	A,R4
;	CJNE	A,#20H,COMFAIL  ;SHOULD = 20H

	JMP	WAIT

COMFAIL:
	REFRESH
	CLR	C
	CALL	STG0
	CLR	C
	CALL	STG1
	CLR	C
	CALL	STG2
	CLR	C
	CALL	STG3
	CLR	C
	CALL	STG4
	CLR	C
	CALL	STG5
	CLR	C
	CALL	STG6
	CLR	C
	CALL	STG7
	CLR	C
	CALL	STG8
	CLR	C
	CALL	STG9
	CLR	C
	CALL	STG10
	CLR	C
	CALL	STG11
COMFAIL1:
	SETB	C
	CALL STG8	;DRIVES ON
	CALL	PAWS
	CALL	PAWS
	CLR	C
	CALL	STG8	;DRIVES OFF
	CALL	PAWS
	JMP	COMFAIL1

;TURN OFF ALL LEDS IN GROUP EXCEPT CURRENT SELECTION (R0)
GPOFF:
	NOP
	PUSH 	ACC
	PUSH	B
	MOV	A,@R0		;SWITCH TYPE
	MOV	B,A		;B = GROUP #
	;SET UP R3.R2 AS MASK
	MOV	R3,#0FFH
	MOV	R2,#0FEH
	MOV	R1,#TYPE
GPOFF1:
	;SKIP IF R0=R1:
	CLR	C
	MOV	A,R1
	SUBB	A,R0
	JZ	GPOFF2
	MOV	A,@R1
	CLR	C
	SUBB	A,B
	JNZ	GPOFF2		;JMP IF NOT A MEMBER OF GROUP
	;MEMBER OF GROUP
	MOV	A,R3
	ANL	LEDT,A
	MOV	A,R2
	ANL	LEDT+1,A
GPOFF2:
	INC	R1
	;SHIFT MASK LEFT 1:
	SETB	C
	MOV	A,R2
	RLC	A
	MOV	R2,A
	MOV	A,R3
	RLC	A
	MOV	R3,A
	JB	ACC.4,GPOFF1
	POP	B
	POP	ACC
RET

$INCLUDE(UARTIO.asm)

;IIC SUBS
IDLY:
;	NOP
;	NOP
;	NOP
;	NOP
;	NOP
;	NOP
;	NOP
;	NOP

	;NOP          ;REMOVED 11-6-2012
	;PUSH	B      ;REMOVED 11-6-2012
	;MOV	B,#2	;CHANGED FROM #4 TO #2 5-2-2012
	;DJNZ	B,$
	;POP	B      ;REMOVED 11-6-2012
	RET

IWRITEBYTE_ORIG:
	NOP
	PUSH	B
	MOV	B,#8
	CLR	SCLK
WB0:	RLC	A
	MOV	SDA,C
	CALL	IDLY
	SETB	SCLK
	CALL	IDLY
	CLR	SCLK
	DJNZ	B,WB0
	;ACK BIT:
	SETB	SDA
	CALL	IDLY
	SETB	SCLK
;	CALL	IDLY
	MOV	C,SDA	;SHOULD BE 0
	CALL	IDLY
	CLR	SCLK
	POP	B
	RET

;UNRAPPED:
IWRITEBYTE:
	CLR	SCLK

	RLC	A       ;A7
	MOV	SDA,C
	CALL	IDLY
	SETB	SCLK
	CALL	IDLY
	CLR	SCLK
	RLC	A       ;A6
	MOV	SDA,C
	CALL	IDLY
	SETB	SCLK
	CALL	IDLY
	CLR	SCLK
	RLC	A       ;A5
	MOV	SDA,C
	CALL	IDLY
	SETB	SCLK
	CALL	IDLY
	CLR	SCLK
	RLC	A       ;A4
	MOV	SDA,C
	CALL	IDLY
	SETB	SCLK
	CALL	IDLY
	CLR	SCLK
	RLC	A       ;A3
	MOV	SDA,C
	CALL	IDLY
	SETB	SCLK
	CALL	IDLY
	CLR	SCLK
	RLC	A       ;A2
	MOV	SDA,C
	CALL	IDLY
	SETB	SCLK
	CALL	IDLY
	CLR	SCLK
	RLC	A       ;A1
	MOV	SDA,C
	CALL	IDLY
	SETB	SCLK
	CALL	IDLY
	CLR	SCLK
	RLC	A       ;A0
	MOV	SDA,C
	CALL	IDLY
	SETB	SCLK
	CALL	IDLY
	CLR	SCLK

	;ACK BIT:
	SETB	SDA
	CALL	IDLY
	SETB	SCLK
	MOV	C,SDA	;SHOULD BE 0
	CALL	IDLY
	CLR	SCLK
	RET


IREADBYTE_ORIG:
	NOP
	SETB	SDA
	PUSH	B
	MOV	B,#8
	CLR	SCLK
RB0:	CALL	IDLY
	MOV	C,SDA
	SETB	SCLK
	RLC	A
	CALL	IDLY
	CLR	SCLK
	DJNZ	B,RB0
	;ACK BIT:
	CLR	SDA
	CALL	IDLY
	SETB	SCLK
	CALL	IDLY
	CLR	SCLK
	SETB	SDA
;	CLR	SCLK
	POP	B
	RET

;UNWRAPPED:
IREADBYTE:
	SETB	SDA
	CLR	SCLK

	CALL	IDLY
	MOV	C,SDA
	SETB	SCLK
	RLC	A       ;BIT 7
	CALL	IDLY
	CLR	SCLK
	CALL	IDLY
	MOV	C,SDA
	SETB	SCLK
	RLC	A       ;BIT 6
	CALL	IDLY
	CLR	SCLK
	CALL	IDLY
	MOV	C,SDA
	SETB	SCLK
	RLC	A       ;BIT 5
       	CALL	IDLY
	CLR	SCLK
	CALL	IDLY
	MOV	C,SDA
	SETB	SCLK
	RLC	A       ;BIT 4
       	CALL	IDLY
	CLR	SCLK
	CALL	IDLY
	MOV	C,SDA
	SETB	SCLK
	RLC	A       ;BIT 3
	CALL	IDLY
	CLR	SCLK
	CALL	IDLY
	MOV	C,SDA
	SETB	SCLK
	RLC	A       ;BIT 2
	CALL	IDLY
	CLR	SCLK
	CALL	IDLY
	MOV	C,SDA
	SETB	SCLK
	RLC	A       ;BIT 1
	CALL	IDLY
	CLR	SCLK
	CALL	IDLY
	MOV	C,SDA
	SETB	SCLK
	RLC	A       ;BIT 0
	CALL	IDLY
	CLR	SCLK

	;ACK BIT:
	CLR	SDA
	CALL	IDLY
	SETB	SCLK
	CALL	IDLY
	CLR	SCLK
	SETB	SDA
	RET

IREADBYTEL_ORIG:
	NOP
	SETB	SDA
	PUSH	B
	MOV	B,#8
	CLR	SCLK
RBL0:	CALL	IDLY
	MOV	C,SDA
	SETB	SCLK
	RLC	A
	CALL	IDLY
	CLR	SCLK
	DJNZ	B,RBL0
	;-ACK BIT:
	SETB	SDA
	CALL	IDLY
	SETB	SCLK
	CALL	IDLY
	CLR	SCLK
	POP	B
	RET

;UNWRAPPED:
IREADBYTEL:
	SETB	SDA
	CLR	SCLK
	CALL	IDLY
	MOV	C,SDA
	SETB	SCLK
	RLC	A       ;BIT 7
	CALL	IDLY
	CLR	SCLK
	CALL	IDLY
	MOV	C,SDA
	SETB	SCLK
	RLC	A       ;BIT 6
	CALL	IDLY
	CLR	SCLK
	CALL	IDLY
	MOV	C,SDA
	SETB	SCLK
	RLC	A       ;BIT 5
	CALL	IDLY
	CLR	SCLK
	CALL	IDLY
	MOV	C,SDA
	SETB	SCLK
	RLC	A       ;BIT 4
	CALL	IDLY
	CLR	SCLK
	CALL	IDLY
	MOV	C,SDA
	SETB	SCLK
	RLC	A       ;BIT 3
	CALL	IDLY
	CLR	SCLK
	CALL	IDLY
	MOV	C,SDA
	SETB	SCLK
	RLC	A       ;BIT 2
	CALL	IDLY
	CLR	SCLK
	CALL	IDLY
	MOV	C,SDA
	SETB	SCLK
	RLC	A       ;BIT 1
	CALL	IDLY
	CLR	SCLK
	CALL	IDLY
	MOV	C,SDA
	SETB	SCLK
	RLC	A       ;BIT 0
	CALL	IDLY
	CLR	SCLK

	;-ACK BIT:
	SETB	SDA
	CALL	IDLY
	SETB	SCLK
	CALL	IDLY
	CLR	SCLK
	RET


IWSTRT:	;START OF I2C WRITE SEQUENCE
	NOP
	SETB	SDA
	SETB	SCLK
	SETB	ADD0
	SETB	ADD1
	CALL	IDLY
	CLR	SDA
	CALL	IDLY
	CLR	SCLK
	MOV	A,#05EH	;DEVICE ADDRS,WRITE SELECT
	CALL	IWRITEBYTE
	MOV	A,R7	;HI ORDER ADDRESS
	CALL	IWRITEBYTE
	MOV	A,R6	;LOW ORDER ADDRESS
	CALL	IWRITEBYTE
	RET

IRSTRT:	;START OF I2C READ SEQUENCE
	NOP
	SETB	SDA
	SETB	SCLK
	SETB	ADD0
	SETB	ADD1
	CALL	IDLY
	CLR	SDA
	CALL	IDLY
	CLR	SCLK
	MOV	A,#05FH	;DEVICE ADDRS,READ SELECT
	CALL	IWRITEBYTE
	RET

ISTP:	;END OF I2C SEQUENCE
	CLR	SDA
	CLR	SCLK
	CALL	IDLY
	SETB	SCLK
	CALL	IDLY
	SETB	SDA
	CALL	IDLY
	RET

I2C_SEND16:
	NOP
	CRON    ;BACK IN 11-6-2012
	CALL	IWSTRT
;	MOV	A,R5	;DATA HI
;	CALL	IWRITEBYTE
;	MOV	A,R4
;	CALL	IWRITEBYTE
	CALL	I2C_SENDWRD
	CALL	ISTP
	CROF    ;BACK IN 11-6-2012
	RET

I2C_SENDWRD:
	NOP
	MOV	A,R5	;DATA HI
	CALL	IWRITEBYTE
	MOV	A,R4
	CALL	IWRITEBYTE
	RET


I2C_RCV:
	NOP
	CRON    ;BACK IN 11-6-2012
	CALL	I2C_RCVSTRT
	CALL	I2C_RCVWRDL
	CROF    ;BACK IN 11-6-2012
	RET

I2C_RCVSTRT:
	NOP
	CALL	IWSTRT	;SET REGISTER ADDRESS
	CALL	ISTP
	CALL	IRSTRT
	RET

I2C_RCVWRD:
	CALL	IREADBYTE
	MOV	R5,A
	CALL	IREADBYTE
	MOV	R4,A
	RET

I2C_RCVWRDL:
	CALL	IREADBYTE
	MOV	R5,A
	CALL	IREADBYTEL
	MOV	R4,A
	CALL	ISTP
	RET

;SPI SUBS
;SEND AND RECEIVE A BYTE FROM SPI. A = BYTE TO SEND, A = RECEIVED BYTE
SPI_TXRX:
	NOP
	PUSH	B
	MOV	B,#8
SPILOOP:
	SETB	SPI_CLK
	SPIWAIT
	RLC	A
	MOV	SPI_OUT,C       ;CLK 1->0: OUTPUT DATA
	CLR	SPI_CLK
	SPIWAIT
	MOV	C,SPI_IN       	;CLK 0->1: READ DATA
	MOV	ACC.0,C
	DJNZ	B,SPILOOP
	SETB	SPI_CLK
	SPIWAIT
	POP	B
	RET



;TRANSMIT THE 16 BIT WORD IN R5.R4 TO LED DRIVER
SPI_SEND:
	CRON
	MOV	A,LEDCS
	JNZ	SPIS1
	CLR	LEDCS1	;CHIP SEL. ON
	JMP	SPIS2
SPIS1:
	CLR	LEDCS2
SPIS2:
	MOV	A,R5
	CALL	SPI_TXRX
	MOV	A,R4
	CALL	SPI_TXRX
	SETB	LEDCS1	;CHIP SEL. OFF
	SETB	LEDCS2
	CROF
	RET

;TRANSMIT THE 16 BIT WORD IN R5.R4 TO REGISTER # R7.R6
CAP_SEND16:
	JNB	SPIF,IIC16
	CALL	SPI_SEND16
	RET
IIC16:	CALL	I2C_SEND16
RET

SPI_SEND16:
	CRON
	CLR	CAPCS	;CHIP SEL. ON
	MOV	A,R7      ;HIGH ORDER BYTE OF ADDRESS
	ORL	A,#0E0H 	;ADD THE CONTROL BITS
	CALL	SPI_TXRX
	MOV	A,R6   ;LOW ORDER BYTE OF ADDRESS
	CALL	SPI_TXRX
	MOV	A,R5 ;HIGH ORDER BYTE OF DATA
	CALL	SPI_TXRX
	MOV	A,R4   ;LOW ORDER BYTE OF DATA
	CALL	SPI_TXRX
	SETB	CAPCS	;CHIP SEL. OFF
	SPIWAIT
	CROF
	RET


;start up cap chip
CAPSTART:
	MOV	R7,#0
	MOV	R6,#2H
	CALL	CAP_RCV         ;READ TO CLEAR SELF-CLEARING BITS
	;SET CAL ENABLE BITS:
	MOV	R7,#0
	MOV	R6,#1H
	MOV	R5,#0FFH
	MOV	R4,#0FFH
	CALL	CAP_SEND16
	;FORCE RECAL:
	MOV	R7,#0
	MOV	R6,#2
	CALL	CAP_RCV
	MOV	A,#40H	;FORCED RECAL BIT
	ORL	A,R5
	MOV	R5,A
	CALL	CAP_SEND16
	RET


;LOAD CHIP FROM FLASH:
SET_FROM_FLASH:
	JB	SPIF,SFSSPI
	JMP	SFSIIC
SFSSPI:
	;RESET REGISTERS
	MOV	R7,#0
	MOV	R6,#0
	MOV	R5,#04H
	MOV	R4,#00H
	CALL	SPI_SEND16
	;WAIT FOR A WHILE:
	mov	r0,#0
	mov	r1,#0
sff1:
	djnz	r1,$
	djnz	r0,sff1

	;SET FLASH PAGE MEMORY TO 0:
	MOV	EADRL,#0
	MOV	EADRH,#0
	;LOAD BANK 2:
	CLR	CAPCS
	MOV	R0,#48	;#16 BIT REGISTERS/2
	MOV	R7,#0E0H  ;CONTROL BITS AND HIGH ORDER BITS OF ADDRESS
	MOV	R6,#080H     ;BANK 2 STARTING ADDRESS
	MOV	A,R7
	CALL	SPI_TXRX
	MOV	A,R6
	CALL	SPI_TXRX
SFR0:
	GET4
	MOV	A,EDATA2  	;MSB
	CALL	SPI_TXRX
	MOV	A,EDATA1	;LSB
	CALL	SPI_TXRX
	MOV	A,EDATA4 	;MSB
	CALL	SPI_TXRX
	MOV	A,EDATA3  	;LSB
	CALL	SPI_TXRX
	DJNZ	R0,SFR0
	SETB	CAPCS	;CHIP SELECT OFF

	;LOAD PART OF BANK 1:
	MOV	R0,#4
	MOV	R7,#0E0H
	MOV	R6,#0
	CLR	CAPCS	;CHIP SELECT ON
	MOV	A,R7
	CALL	SPI_TXRX
	MOV	A,R6
	CALL	SPI_TXRX
SFR1:
	GET4
	MOV	A,EDATA2
	CALL	SPI_TXRX
	MOV	A,EDATA1
	CALL	SPI_TXRX
	MOV	A,EDATA4
	CALL	SPI_TXRX
	MOV	A,EDATA3
	CALL	SPI_TXRX
	DJNZ	R0,SFR1
	SETB	CAPCS	;CHIP SELECT OFF
;	CALL	CAPSTART
	RET
SFSIIC:
	;RESET REGISTERS
	MOV	R7,#0
	MOV	R6,#0
	MOV	R5,#04H
	MOV	R4,#00H
	CALL	I2C_SEND16
	;WAIT FOR A WHILE:
	mov	r0,#0
	mov	r1,#0
sff1i:
	djnz	r1,$
	djnz	r0,sff1i

	;SET FLASH PAGE MEMORY TO 0:
	MOV	EADRL,#0
	MOV	EADRH,#0
	;LOAD BANK 2:
	MOV	R0,#48	;#16 BIT REGISTERS/2
	MOV	R7,#00H 	;HIGH ORDER BITS OF ADDRESS
	MOV	R6,#080H     	;BANK 2 STARTING ADDRESS
	CALL	IWSTRT
SFR0I:
	GET4
	MOV	R5,EDATA2  	;MSB
	MOV	R4,EDATA1	;LSB
	CALL	I2C_SENDWRD
	MOV	R5,EDATA4 	;MSB
	MOV	R4,EDATA3  	;LSB
	CALL	I2C_SENDWRD
	DJNZ	R0,SFR0I
	CALL	ISTP

	;LOAD PART OF BANK 1:
	MOV	R0,#4
	MOV	R7,#00H
	MOV	R6,#0
	CALL	IWSTRT
SFR1I:
	GET4
	MOV	R5,EDATA2
	MOV	R4,EDATA1
	CALL	I2C_SENDWRD
	MOV	R5,EDATA4
	MOV	R4,EDATA3
	CALL	I2C_SENDWRD
	DJNZ	R0,SFR1I
	CALL	ISTP
;	CALL	CAPSTART
	RET


;;LOAD CHIP FROM FLASH:
;SET_FROM_FLASHX:
;	;RESET REGISTERS
;	MOV	R7,#0
;	MOV	R6,#0
;	MOV	R5,#04H
;	MOV	R4,#00H
;	CALL	SPI_SEND16
;	;WAIT FOR A WHILE:
;	mov	r0,#0
;	mov	r1,#0
;sff2:
;	djnz	r1,$
;	djnz	r0,sff2
;
;	;SET FLASH PAGE MEMORY TO 0:
;	MOV	EADRL,#0
;	MOV	EADRH,#0
;	;LOAD BANK 2:
;	MOV	R0,#48	;#16 BIT REGISTERS/2
;	MOV	R7,#0H  ;HIGH ORDER BITS OF ADDRESS
;	MOV	R6,#080H     ;BANK 2 STARTING ADDRESS
;SFR0X:
;	GET4
;	MOV	R5,EDATA2  	;MSB
;	MOV	R4,EDATA1	;LSB
;	CALL	SPI_SEND16
;	INCR7R6
;	MOV	R5,EDATA4 	;MSB
;	MOV	R4,EDATA3  	;LSB
;	CALL	SPI_SEND16
;	INCR7R6
;	DJNZ	R0,SFR0X
;
;	;LOAD PART OF BANK 1:
;	MOV	R0,#4
;	MOV	R7,#0H
;	MOV	R6,#0
;SFR1X:
;	GET4
;	MOV	R5,EDATA2
;	MOV	R4,EDATA1
;	CALL	SPI_SEND16
;	INCR7R6
;	MOV	R5,EDATA4
;	MOV	R4,EDATA3
;	CALL	SPI_SEND16
;	INCR7R6
;	DJNZ	R0,SFR1X
;;	CALL	CAPSTART
;	RET

;;LOAD CHIP FROM FLASH WITH VERIFICATION:
;SET_FROM_FLASHV:
;	;RESET REGISTERS
;	MOV	R7,#0
;	MOV	R6,#0
;	MOV	R5,#04H
;	MOV	R4,#00H
;	CALL	SPI_SEND16
;	;WAIT FOR A WHILE:
;	mov	r0,#0
;	mov	r1,#0
;sfv2:
;	djnz	r1,$
;	djnz	r0,sfv2
;	;SET FLASH PAGE MEMORY TO 0:
;	MOV	EADRL,#0
;	MOV	EADRH,#0
;	;LOAD BANK 2:
;	MOV	R0,#48	;#16 BIT REGISTERS/2
;	MOV	R7,#0H  ;HIGH ORDER BITS OF ADDRESS
;	MOV	R6,#080H     ;BANK 2 STARTING ADDRESS
;SFR0V:
;	GET4			;GET 4 BYTES FROM FLASH MEM.
;	MOV	R5,EDATA2  	;MSB
;	MOV	R4,EDATA1	;LSB
;SFL0:	CALL	SPI_SEND16	;SEND FIRST WORD OF GROUP
;	CALL	SPI_RCV		;READ IT BACK
;	MOV	A,R5
;	CJNE	A,EDATA2,SFL0	;REPEAT IF NOT HI ORDER MATCH
;	MOV	A,R4
;	CJNE	A,EDATA1,SFL0	;REPEAT IF NOT LO ORDER MATCH
;	INCR7R6			;INCREMENT R7.R6 ADDRESS
;	MOV	R5,EDATA4 	;MSB
;	MOV	R4,EDATA3  	;LSB
;SFL1:	CALL	SPI_SEND16	;SEND SECOND WORD OF GROUP
;	CALL	SPI_RCV		;READ IT BACK
;	MOV	A,R5
;	CJNE	A,EDATA4,SFL1	;REPEAT IF NOT HI ORDER MATCH
;	MOV	A,R4
;	CJNE	A,EDATA3,SFL1	;REPEAT IF NOT LO ORDER MATCH
;	INCR7R6
;	DJNZ	R0,SFR0V
;
;	;LOAD PART OF BANK 1:
;	MOV	R0,#4
;	MOV	R7,#0H
;	MOV	R6,#0
;SFR1V:
;	GET4
;	MOV	R5,EDATA2
;	MOV	R4,EDATA1
;SFL2:	CALL	SPI_SEND16
;	CALL	SPI_RCV
;	MOV	A,R5
;	CJNE	A,EDATA2,SFL2
;	MOV	A,R4
;	CJNE	A,EDATA1,SFL2
;	INCR7R6
;	MOV	R5,EDATA4
;	MOV	R4,EDATA3
;SFL3:	CALL	SPI_SEND16
;	CALL	SPI_RCV
;	MOV	A,R5
;	CJNE	A,EDATA4,SFL3
;	MOV	A,R4
;	CJNE	A,EDATA3,SFL3
;	INCR7R6
;	DJNZ	R0,SFR1V
;
;	MOV	R7,#0
;	MOV	R6,#2H
;	CALL	SPI_RCV         ;READ TO CLEAR SELF-CLEARING BITS
;
;	;SET CAL ENABLE BITS:
;	MOV	R7,#0
;	MOV	R6,#1H
;SFL4:	MOV	R5,#0FFH
;	MOV	R4,#0FFH
;	CALL	SPI_SEND16
;	CALL	SPI_RCV
;        CJNE	R5,#0FH,SFL4
;        CJNE	R4,#0FFH,SFL4
;	RET

;COMPARE LOADED PARAMS WITH THOSE STORED IN FLASH
;RETURN WITH A=1 IF MATCH, 0 IF DIFFERENT
verify:
	JB	SPIF,VERIFYSPI
	JMP	VERIFYIIC
VERIFYSPI:
	;SET FLASH PAGE MEMORY TO 0:
	MOV	EADRL,#0
	MOV	EADRH,#0
	;CHECK BANK 2:
	MOV	R0,#48	;#16 BIT REGISTERS/2
	CLR	CAPCS
	MOV	A,#0E4H  ;CONTROL BITS AND HIGH ORDER BITS OF ADDRESS
	CALL	SPI_TXRX
	MOV	A,#080H		;BANK 2 STARTING ADDRESS
	CALL	SPI_TXRX
VFY0:
	GET4
	MOV	A,#0
	CALL	SPI_TXRX
	CJNE	A,EDATA2,VFYBAD	;A = HIGH ORDER BYTE OF RCV'D DATA
	MOV	A,#0
	CALL	SPI_TXRX
	CJNE	A,EDATA1,VFYBAD	;A = LOW ORDER BYTE OF RCV'D DATA
	MOV	A,#0
	CALL	SPI_TXRX
	CJNE	A,EDATA4,VFYBAD	;A = HIGH ORDER BYTE OF RCV'D DATA
	MOV	A,#0
	CALL	SPI_TXRX
	CJNE	A,EDATA3,VFYBAD	;A = LOW ORDER BYTE OF RCV'D DATA
	DJNZ	R0,VFY0
	;BANK 2 CHECKED
	SETB	CAPCS
	;CHECK BANK 1:
	MOV	R0,#4	;#16 BIT REGISTERS/2
	MOV	A,#0E4H  ;CONTROL BITS AND HIGH ORDER BITS OF ADDRESS
	CLR	CAPCS
	CALL	SPI_TXRX
	MOV	A,#0H		;BANK 1 STARTING ADDRESS
	CALL	SPI_TXRX
VFY1:
	GET4
	MOV	A,#0
	CALL	SPI_TXRX
	CJNE	A,EDATA2,VFYBAD	;A = HIGH ORDER BYTE OF RCV'D DATA
	MOV	A,#0
	CALL	SPI_TXRX
	CJNE	A,EDATA1,VFYBAD	;A = LOW ORDER BYTE OF RCV'D DATA
	MOV	A,#0
	CALL	SPI_TXRX
	CJNE	A,EDATA4,VFYBAD	;A = HIGH ORDER BYTE OF RCV'D DATA
	MOV	A,#0
	CALL	SPI_TXRX
	CJNE	A,EDATA3,VFYBAD	;A = LOW ORDER BYTE OF RCV'D DATA
	DJNZ	R0,VFY1
	MOV	A,#1
	JMP	VFYEND
VFYBAD:	MOV	A,#0
VFYEND:
	SETB	CAPCS	;CHIP SELECT OFF
	RET
VERIFYIIC:
	;SET FLASH PAGE MEMORY TO 0:
	MOV	EADRL,#0
	MOV	EADRH,#0
	;CHECK BANK 2:
	MOV	R0,#48	;#16 BIT REGISTERS/2
	MOV	R7,#0H  ;HIGH ORDER BITS OF ADDRESS
	MOV	R6,#080H		;BANK 2 STARTING ADDRESS
	CALL	I2C_RCVSTRT
VFY0I:
	GET4
	CALL	IREADBYTE
	CJNE	A,EDATA2,VFYBADI	;A = HIGH ORDER BYTE OF RCV'D DATA
	CALL	IREADBYTE
	CJNE	A,EDATA1,VFYBADI	;A = LOW ORDER BYTE OF RCV'D DATA
	CALL	IREADBYTE
	CJNE	A,EDATA4,VFYBADI	;A = HIGH ORDER BYTE OF RCV'D DATA
	MOV	A,R0
	DEC	A
	JZ	LSTB
	CALL	IREADBYTE
	JMP	VFY01I
LSTB:
	CALL	IREADBYTEL
VFY01I:
	CJNE	A,EDATA3,VFYBADI	;A = LOW ORDER BYTE OF RCV'D DATA
	DJNZ	R0,VFY0I
	;BANK 2 CHECKED
	;CHECK BANK 1:
	MOV	R0,#4	;#16 BIT REGISTERS/2
	MOV	R7,#0H  ;HIGH ORDER BITS OF ADDRESS
	MOV	R6,#0H		;BANK 1 STARTING ADDRESS
	CALL	I2C_RCVSTRT
VFY1I:
	GET4
	CALL	IREADBYTE
	CJNE	A,EDATA2,VFYBADI	;A = HIGH ORDER BYTE OF RCV'D DATA
	CALL	IREADBYTE
	CJNE	A,EDATA1,VFYBADI	;A = LOW ORDER BYTE OF RCV'D DATA
	CALL	IREADBYTE
	CJNE	A,EDATA4,VFYBADI	;A = HIGH ORDER BYTE OF RCV'D DATA
	MOV	A,R0
	DEC	A
	JZ	VFY2
	CALL	IREADBYTE
	JMP	VFY3
VFY2:
	CALL	IREADBYTEL
VFY3:
	CJNE	A,EDATA3,VFYBAD	;A = LOW ORDER BYTE OF RCV'D DATA
	DJNZ	R0,VFY1I
	MOV	A,#1
	JMP	VFYENDI
VFYBADI:
	MOV	A,#0
VFYENDI:
	RET


;RECEIVE A 16 BIT WORD
CAP_RCV:
	JNB	SPIF,CRI	;JMP IF IIC CHIP
	CALL	SPI_RCV
	RET
CRI:
	CALL	I2C_RCV
	RET

SPI_RCV:
	CRON
	CLR	CAPCS	;CHIP SEL. ON
	MOV	A,R7	     	;HIGH ORDER BYTE OF ADDRESS
	ORL	A,#0E4H         ;ADD CONTROL BITS
	CALL	SPI_TXRX
	MOV	A,R6	;LOW ORDER BYTE OF ADDRESS
	CALL	SPI_TXRX
	MOV	A,#0
	CALL	SPI_TXRX
	MOV	R5,A		;HIGH ORDER BYTE OF RCV'D DATA
	MOV	A,#0
	CALL	SPI_TXRX
	MOV	R4,A		;LOW ORDER BYTE OF RCV'D DATA
	SETB	CAPCS	;CHIP SEL. OFF
	CROF
	RET

;CONFIGURE PORT AS LED DRIVER. PORT # IN A
LED_DRIVER:
	NOP
	PUSH	ACC
	MOV	R4,#0
	clr	c
	RRC	A
	clr	c
	RRC	A
	ANL	A,#01FH
	ADD	A,#8
	MOV	R5,A
	CALL	SPI_SEND
	POP	ACC
	RET

;TURN LED ON. PORT # IN A
LED_ON:
	NOP
	PUSH	ACC
	MOV	R4,#1
	ADD	A,#020H
	MOV	R5,A
	CALL	SPI_SEND
	POP	ACC
	RET

;TURN LED OFF. PORT # IN A
LED_OFF:
	NOP
	PUSH	ACC
	MOV	R4,#0
	ADD	A,#020H
	MOV	R5,A
	CALL	SPI_SEND
	POP	ACC
	RET

;SET INTENSITY LEVEL. PORT # IN A, INTENSITY LEVEL (0-15) IN R0
LED_LEVEL:
	NOP
	PUSH	ACC
	clr	c
	RRC	A
	ADD	A,#010H
	MOV	R5,A
	;FOR NOW, PUT SAME LEVEL IN BOTH PORTS:
	MOV	A,R0
	SWAP	A
	ORL	A,R0
	MOV	R4,A
	CALL	SPI_SEND
	POP	ACC
	RET

WFT:
	JNB	TICK,WFT
	CLR	TICK
	RET

;ramp up led a
RAMPUP:
	CALL	LED_ON
	CLR	TICK
	MOV	R0,#0
RU1:	CALL	LED_LEVEL
	CALL	WFT
	INC	R0
	CJNE	R0,#16,RU1
	RET

;ramp down led a
RAMPDN:
	CLR	TICK
	MOV	R0,#14
RD1:	CALL	LED_LEVEL
	CALL	WFT
	DEC	R0
	CJNE	R0,#0FFH,RD1
	CALL	LED_OFF
	RET

LED_CONFIG:
	MOV	R5,#04H
	MOV	R4,#041H
	CALL	SPI_SEND
	MOV	A,#12	;FIRST LED #
LED_NEXT:
	CALL	LED_DRIVER
	MOV	R0,LEDI
	CALL	LED_LEVEL
        CALL	LED_OFF
	INC	A
	CJNE	A,#32,LED_NEXT
	RET

;;SEPARATOR:      DB 10,13,0
SEPARATOR:      DB 13,0
;DIVIDE MANTISSA AT R1 BY 16. SET A TO REMAINDER IN ASCII (HEX)
MDIV16:
	MOV	R2,#MSIZ
	MOV	B,#0
	MOV	A,R1
	PUSH 	ACC		;SAVE R1
MD16A:
	MOV	A,@R1           ;GET BYTE
	SWAP	A               ;SHIFT BY 4
	PUSH	ACC             ;TEMPORARLY SAVE
	ANL	A,#0FH          ;MASK OFF HIGH NIBBLE
	ORL	A,B             ;REPLACE HIGH NIBBLE WITH LAST HI NIBBLE
	MOV	@R1,A           ;SAVE SHIFTED BYTE
	POP	B               ;GET SHIFTER BYTE
	ANL	B,#0F0H         ;MASK OFF LOW NIBBLE
	INC	R1
	DJNZ	R2,MD16A
	MOV	A,B
	SWAP	A
	CJNE	A,#10,$+3
	JC	MD16B		;JMP IF A < 10
	ADD	A,#7
MD16B:	ADD	A,#30H
	POP	B
	MOV	R1,B		;RESTORE R1
	RET

;MULTIPLY MANTISSA AT R1 BY 16
MMUL16:
	MOV	R2,#MSIZ
	MOV	B,#0
	MOV	A,#MSIZ-1
	ADD	A,R1
	MOV	R1,A           	;R1 POINTS TO LEAST SIG. BYTE
MM16A:
	MOV	A,@R1           ;GET BYTE
	SWAP	A               ;SHIFT BY 4
	PUSH	ACC		;SAVE FOR LATER
	ANL	A,#0F0H         ;MASK OFF LOW NIBBLE
	ORL	A,B             ;REPLACE WITH LOW NIBBLE FROM PREVIOUS SHIFT
	MOV	@R1,A           ;SAVE BYTE
	POP	B               ;GET SHIFTED BYTE
	ANL	B,#0FH          ;MASK OFF HIGH NIBBLE
	DEC	R1
	DJNZ	R2,MM16A
	RET

;DIVIDE MANTISSA AT R1 BY 10. set a to remainder in ascii. uses r0,r1,r2,r3,a,b
MDIV10:
	mov	r2,#MSIZ*2	;number of nibbles
	MOV	a,#0            ;initialize remainder
	push	acc
	mov	a,#MSIZ-1
	add	a,r1
	mov	r3,a            ;points to least sig byte of mantissa
mdl1:
	mov	a,r3
	mov	r0,a            ;r0 points to least sig byte.(for upcoming shift)
	pop	acc             ;previous remainder
	swap	a
	mov	b,a		;previous remainder in high order nibble of b
	MOV	A,@R1
	SWAP	A               ;move remainder to high order nibble
	ANL	A,#0FH          ;a = highest order nibble
	orl	a,b             ;add in the previous remainder
	MOV	B,#10
	DIV	AB
	PUSH	B               ;save remainder
	SHLMANTA                ;shift mantissa lift 1 nibble. shift in quotient nibble.
	djnz	r2,mdl1
	pop	acc		;final remainder
	add	a,#'0'		;convert to ascii char.
     	ret

;print the mantissa at r1 in decimal
out5:
	mov	r4,#5	;number of digits
	mov	r5,#outbuf+5;was 10
	mov	r7,#0	;zero counter
p10a:	call	mdiv10
	cjne	a,#'0',p10ab
	inc	r7
	jmp	p10aa
p10ab:	mov	r7,#0
p10aa:	push	acc
	dec	r5
	mov	a,r5
	mov	r0,a
	pop	acc
	mov	@r0,a
	djnz	r4,p10a
	mov	a,#5   ;number of digits
	clr	c
	subb	a,r7    ;number of digits with leading zeros removed
	jnz	p10ac
	;number is zero: print 1 zero
	mov	a,#'0'
	call	SENDCHAR
	jmp	p10ret
p10ac:	mov	r4,a    ;r4 = # digits to print
	mov	a,r5
	add	a,r7
	mov	r5,a
p10b:	mov	a,r5
	mov	r0,a
	mov	a,@r0
	call	SENDCHAR
	inc	r5
	djnz	r4,p10b
p10ret:	ret


;print the mantissa at r1 in hex
out4h:
	mov	r4,#4	;number of digits
	mov	r5,#outbuf+4
	mov	r7,#0	;zero counter
p4a:	call	mdiv16
	cjne	a,#'0',p4ab
	inc	r7
	jmp	p4aa
p4ab:	mov	r7,#0
p4aa:	push	acc
	dec	r5
	mov	a,r5
	mov	r0,a
	pop	acc
	mov	@r0,a
	djnz	r4,p4a
	mov	a,#4   ;number of digits
	clr	c
	subb	a,r7    ;number of digits with leading zeros removed
	jnz	p4ac
	;number is zero: print 1 zero
	mov	a,#'0'
	call	SENDCHAR
	jmp	p4ret
p4ac:	mov	r4,a    ;r4 = # digits to print
	mov	a,r5
	add	a,r7
	mov	r5,a
p4b:	mov	a,r5
	mov	r0,a
	mov	a,@r0
	call	SENDCHAR
	inc	r5
	djnz	r4,p4b
p4ret:	ret




ILOAD:
	;POINT TO FLASH PAGE 0:
	MOV	EADRL,#0
	MOV	EADRH,#0
	;REGISTER BANK 2
	MOV	DPTR,#PG2
	MOV	R0,#52;54
ILP1:
	CLR	A
        MOVC	A,@A+DPTR	;MSB
        INC	DPTR
	MOV	EDATA2,A
	CLR	A
        MOVC	A,@A+DPTR	;LSB
        INC	DPTR
	MOV	EDATA1,A
	CLR	A
        MOVC	A,@A+DPTR	;MSB
        INC	DPTR
	MOV	EDATA4,A
	CLR	A
        MOVC	A,@A+DPTR	;LSB
        INC	DPTR
	MOV	EDATA3,A
	;WRITE 4 BYTES TO FLASH:
	MOV	ECON,#5 	;ERASE
	MOV	ECON,#2		;PROGRAM
	INCEAD
	SETB    WDWR
	SETB    WDE	;REFRESH WATCHDOG
	DJNZ	R0,ILP1
	RET

ILOAD_FC:
	;POINT TO FLASH PAGE 0:
	MOV	EADRL,#0
	MOV	EADRH,#0
	;REGISTER BANK 2
	MOV	R7,#0
	MOV	R6,#80H
	MOV	R0,#48 	;NUMBER OF 4 BYTE GROUPS
ILPFC1:
	CALL	CAP_RCV
	INCR7R6
	MOV	EDATA2,R5
	MOV	EDATA1,R4
	CALL	CAP_RCV
	INCR7R6
	MOV	EDATA4,R5
	MOV	EDATA3,R4
	MOV	ECON,#5
	MOV	ECON,#2
	INCEAD
	SETB    WDWR
	SETB    WDE	;REFRESH WATCHDOG
	DJNZ	R0,ILPFC1
	;LEAVE REGISTER BANK 0 ALONE
;	MOV	R7,#0
;	MOV	R6,#0
;	MOV	R0,#3 	;NUMBER OF 4 BYTE GROUPS
;ILPFC2:
;	CALL	SPI_RCV
;	INCR7R6
;	MOV	EDATA2,R5
;	MOV	EDATA1,R4
;	CALL	SPI_RCV
;	INCR7R6
;	MOV	EDATA4,R5
;	MOV	EDATA3,R4
;	MOV	ECON,#5
;	MOV	ECON,#2
;	INCEAD
;	SETB    WDWR
;	SETB    WDE	;REFRESH WATCHDOG
;	DJNZ	R0,ILPFC2
	RET

;*** DEFAULT SETTINGS: ***
PG2:
;SWITCH 0
; 65534         - Connection Mem 0 0x(80) =
DW	 0FFFEH
; 16383         - Connection Mem 1 0x(81) =
DW	  3FFFH
;          - OffSet Control 0x(82) =
DW	  2F00H
; 9766          - Sens Control   0x(83)  =
DW	  2626H
;           - Neg Offset Val 0x(84)  =
DW	  2900H
; 8000          - Pos Offset Val 0x(85)  =
DW	  1F40H
; 15000         - Pos Maxim  Val 0x(86)  =
DW	  3A98H
; 15000         - Neg Maxim  Val 0x(87)  =
DW	  3A98H
;SWITCH 1
; 65531         - Connection Mem 0 0x(88) =
 DW	 0FFFBH
; 16383         - Connection Mem 1 0x(89) =
 DW	 3FFFH
; 2560          - OffSet Control 0x(8A) =
DW	  0700H
; 9766          - Sens Control   0x(8B)  =
 DW	 2626H
;           - Neg Offset Val 0x(8C)  =
 DW	 1100H
; 1000          - Pos Offset Val 0x(8D)  =
 DW	 3E8H
; 1300          - Pos Maxim  Val 0x(8E)  =
 DW	 514H
; 13000         - Neg Maxim  Val 0x(8F)  =
 DW	 32C8H
 ;SWITCH 2
; 65519         - Connection Mem 0 0x(90) =
 DW	 0FFEFH
; 16383         - Connection Mem 1 0x(91) =
 DW	 3FFFH
; 2560          - OffSet Control 0x(92) =
 DW	 0700H
; 9766          - Sens Control   0x(93)  =
 DW	 2626H
;           - Neg Offset Val 0x(94)  =
 DW	 1100H
; 350           - Pos Offset Val 0x(95)  =
 DW	 15EH
; 732           - Pos Maxim  Val 0x(96)  =
 DW	 2DCH
; 13000         - Neg Maxim  Val 0x(97)  =
 DW	 32C8H
 ;SWITCH 3
; 65471         - Connection Mem 0 0x(98) =
 DW	 0FFBFH
; 16383         - Connection Mem 1 0x(99) =
 DW	 3FFFH
; 2560          - OffSet Control 0x(9A) =
 DW	 0700H
; 9766          - Sens Control   0x(9B)  =
 DW	 2626H
;           - Neg Offset Val 0x(9C)  =
 DW	 1100H
; 150           - Pos Offset Val 0x(9D)  =
 DW	 96H
; 250           - Pos Maxim  Val 0x(9E)  =
 DW	 0FAH
; 13000         - Neg Maxim  Val 0x(9F)  =
 DW	 32C8H
;SWITCH 4
; 65279         - Connection Mem 0 0x(A0) =
 DW	 0FEFFH
; 16383         - Connection Mem 1 0x(A1) =
 DW	 3FFFH
; 2560          - OffSet Control 0x(A2) =
 DW	 0700H
; 9766          - Sens Control   0x(A3)  =
 DW	 2626H
;           - Neg Offset Val 0x(A4)  =
 DW	 1100H
; 300           - Pos Offset Val 0x(A5)  =
 DW	 12CH
; 450           - Pos Maxim  Val 0x(A6)  =
 DW	 1C2H
; 13000         - Neg Maxim  Val 0x(A7)  =
 DW	 32C8H
;SWITCH 5
; 64511         - Connection Mem 0 0x(A8) =
 DW	 0FBFFH
; 16383         - Connection Mem 1 0x(A9) =
 DW	 3FFFH
;         - OffSet Control 0x(AA) =
 DW	 2F00H
; 9766          - Sens Control   0x(AB)  =
 DW	 2626H
;           - Neg Offset Val 0x(AC)  =
 DW	 2900H
; 300           - Pos Offset Val 0x(AD)  =
 DW   12CH
; 400           - Pos Maxim  Val 0x(AE)  =
 DW    190H
; 15000         - Neg Maxim  Val 0x(AF)  =
  DW   3A98H
;SWITCH 6
; 65535         - Connection Mem 0 0x(B0) =
  DW   0FFFFH
; 16379         - Connection Mem 1 0x(B1) =
  DW   3FFBH
;           - OffSet Control 0x(B2) =
  DW   1900H
;           - Sens Control   0x(B3)  =
  DW   2626H
;          - Neg Offset Val 0x(B4)  =
  DW   2B00H
; 450           - Pos Offset Val 0x(B5)  =
  DW   1C2H
; 550           - Pos Maxim  Val 0x(B6)  =
  DW   226H
; 14000         - Neg Maxim  Val 0x(B7)  =
  DW   36B0H
;SWITCH 7
; 65535         - Connection Mem 0 0x(B8) =
  DW   0FFFFH
; 16367         - Connection Mem 1 0x(B9) =
  DW   3FEFH
;           - OffSet Control 0x(BA) =
  DW   1900H
; 9766          - Sens Control   0x(BB)  =
  DW   2626H
;          - Neg Offset Val 0x(BC)  =
  DW   2B00H
; 800           - Pos Offset Val 0x(BD)  =
  DW   320H
; 1350          - Pos Maxim  Val 0x(BE)  =
  DW   546H
; 14000         - Neg Maxim  Val 0x(BF)  =
  DW   36B0H
;SWITCH 8
; 65535         - Connection Mem 0 0x(C0) =
  DW   0FFFFH
; 16319         - Connection Mem 1 0x(C1) =
  DW   3FBFH
;           - OffSet Control 0x(C2) =
  DW   1900H
; 9766          - Sens Control   0x(C3)  =
  DW   2626H
;          - Neg Offset Val 0x(C4)  =
  DW   2B00H
; 350           - Pos Offset Val 0x(C5)  =
  DW   15EH
; 430           - Pos Maxim  Val 0x(C6)  =
  DW   1AEH
; 14000         - Neg Maxim  Val 0x(C7)  =
  DW   36B0H
;SWITCH 9
; 65535         - Connection Mem 0 0x(C8) =
  DW   0FFFFH
; 16127         - Connection Mem 1 0x(C9) =
  DW   3EFFH
;           - OffSet Control 0x(CA) =
  DW   1900H
; 9766          - Sens Control   0x(CB)  =
  DW   2626H
;          - Neg Offset Val 0x(CC)  =
  DW   2B00H
; 400           - Pos Offset Val 0x(CD)  =
  DW   190H
; 700           - Pos Maxim  Val 0x(CE)  =
  DW   2BCH
; 14000         - Neg Maxim  Val 0x(CF)  =
  DW   36B0H
;SWITCH 10
; 65535         - Connection Mem 0 0x(D0) =
  DW   0FFFFH
; 15359         - Connection Mem 1 0x(D1) =
  DW   3BFFH
;           - OffSet Control 0x(D2) =
  DW   1900H
; 9766          - Sens Control   0x(D3)  =
  DW   2626
;          - Neg Offset Val 0x(D4)  =
  DW   2B00H
; 1000          - Pos Offset Val 0x(D5)  =
  DW   3E8H
; 1500          - Pos Maxim  Val 0x(D6)  =
  DW   5DCH
; 14000         - Neg Maxim  Val 0x(D7)  =
  DW   36B0H
;SWITCH 11
; 65535         - Connection Mem 0 0x(D8) =
  DW   0FFFFH
; 12287         - Connection Mem 1 0x(D9) =
  DW   2FFFH
;           - OffSet Control 0x(DA) =
  DW   1900H
; 9766          - Sens Control   0x(DB)  =
  DW   2626H
;          - Neg Offset Val 0x(DC)  =
  DW   2B00H
; 1000          - Pos Offset Val 0x(DD)  =
  DW   3E8H
; 2000          - Pos Maxim  Val 0x(DE)  =
  DW   7D0H
; 14000         - Neg Maxim  Val 0x(DF)  =
  DW   36B0H
  ;*** BANK 0 ***
;            - Power Control (0x00) =
  DW   0B0H
;           - Ambient Control 0 (0x01) =
  DW   0;0FFFFH
;           - Ambient Control 1 (0x02) =
  DW   690H
;           - Ambient Control 2 (0x03) =
  DW   1674H
; 10511         - Ambient Control 3 (0x04) =
  DW   290FH
; 0             - Interrupt Enable 0 (0x05) =
  DW   0H
; 0             - Interrupt Enable 1 (0x06) =
  DW   0H
; 1             - Interrupt Enable 2 (0x07) =
  DW   1H
; 0             - Interrupt Status 0 (0x08) =
  DW   0H
; 0             - Interrupt Status 1 (0x09) =
  DW   0H
; 3969          - Interrupt Status 2 (0x0A) =
  DW   0F81H
  DW	0

LEDS_OFF:
	CALL	LED_OFF
	INC	A
	DJNZ	R0,LEDS_OFF
	RET
LEDS_ON:
	CALL	LED_ON
	INC	A
	DJNZ	R0,LEDS_ON
	RET

;turn leds on if switch pad touched, turn off if not touched
; A = address of first led, r0 = # of leds.
;;; 2 lines are commented out so that on or off command is always sent,
;;;  not just when there is a change.
PAD_TEST:
	JC	PADT1		;JMP IF PAD IS TOUCHED
	;PAD IS OFF
;;;	JNB	TPAD,PADTR	;JMP IF LEDS ARE OFF
	;LEDS ARE ON
	CALL	LEDS_OFF
	CLR	TPAD
	JMP	PADTR
PADT1:
	;PAD IS TOUCHED
;;;	JB	TPAD,PADTR	;JMP IF LEDS ARE ALREADY ON
	CALL	LEDS_ON
	SETB	TPAD
;	CPL    	CLICK
PADTR:
	MOV	C,TPAD
	CLR	TPAD
	RET


;TURN STAGE 0 LAMPS ON IF C IS NON-ZERO, OFF OTHERWISE
STG0:	;LEDS 37-40
	NOP
	PUSH	ACC
	MOV	LEDCS,#1        ;LED DRIVER #
	MOV	A,#28           ;STARTING LED #
	MOV	R0,#4           ;# OF LEDS
	CALL	PAD_TEST
	POP	ACC
	RET

STG1:	;LEDS 35-36
	NOP
	PUSH	ACC
	MOV	LEDCS,#1
	MOV	A,#26           ;STARTING LED #
	MOV	R0,#2           ;# OF LEDS
	CALL	PAD_TEST
	POP	ACC
	RET

STG2:	;LEDS 33-34
	NOP
	PUSH	ACC
	MOV	LEDCS,#1
	MOV	A,#24           ;STARTING LED #
	MOV	R0,#2           ;# OF LEDS
	CALL	PAD_TEST
	POP	ACC
	RET

STG3:	;LEDS 31-32
	NOP
	PUSH	ACC
	MOV	LEDCS,#1
	MOV	A,#22           ;STARTING LED #
	MOV	R0,#2           ;# OF LEDS
	CALL	PAD_TEST
	POP	ACC
	RET

STG4:	;LEDS 29-30
	NOP
	PUSH	ACC
	MOV	LEDCS,#1
	MOV	A,#20           ;STARTING LED #
	MOV	R0,#2           ;# OF LEDS
	CALL	PAD_TEST
	POP	ACC
	RET

STG5:	;LEDS 25-28
	NOP
	PUSH	ACC
	MOV	LEDCS,#1
	MOV	A,#16           ;STARTING LED #
	MOV	R0,#4           ;# OF LEDS
	CALL	PAD_TEST
	POP	ACC
	RET

STG6:	;LEDS 21-24
	NOP
	PUSH	ACC
	MOV	LEDCS,#1
	MOV	A,#12           ;STARTING LED #
	MOV	R0,#4           ;# OF LEDS
	CALL	PAD_TEST
	POP	ACC
	RET

STG7:	;LEDS 17-20
	NOP
	PUSH	ACC
	MOV	LEDCS,#0
	MOV	A,#28           ;STARTING LED #
	MOV	R0,#4           ;# OF LEDS
	CALL	PAD_TEST
	POP	ACC
	RET

STG8:	;LEDS 13-16
	NOP
	PUSH	ACC
	MOV	LEDCS,#0
	MOV	A,#24           ;STARTING LED #
	MOV	R0,#4           ;# OF LEDS
	CALL	PAD_TEST
	POP	ACC
	RET

STG9:	;LEDS 9-12
	NOP
	PUSH	ACC
	MOV	LEDCS,#0
	MOV	A,#20           ;STARTING LED #
	MOV	R0,#4           ;# OF LEDS
	CALL	PAD_TEST
	POP	ACC
	RET

STG10:	;LEDS 5-8
	NOP
	PUSH	ACC
	MOV	LEDCS,#0
	MOV	A,#16           ;STARTING LED #
	MOV	R0,#4           ;# OF LEDS
	CALL	PAD_TEST
	POP	ACC
	RET

STG11:	;LEDS 1-4
	NOP
	PUSH	ACC
	MOV	LEDCS,#0
	MOV	A,#12           ;STARTING LED #
	MOV	R0,#4           ;# OF LEDS
	CALL	PAD_TEST
	POP	ACC
	RET

setbase:
	setb	baseloaded
	mov	r0,#xj
	mov	r1,#xb
	mov	a,@r0		;get hi order x reading
	mov	@r1,a		;save hi order reading
	inc	r0
	inc	r1
	mov	a,@r0		;get lo order reading
	mov	@r1,a		;save lo order reading

	inc	r0
	inc	r1
	mov	a,@r0		;get hi order y reading
	mov	@r1,a		;save hi order reading
	inc	r0
	inc	r1
	mov	a,@r0		;get lo order reading
	mov	@r1,a		;save lo order reading

	inc	r0
	inc	r1
	mov	a,@r0		;get hi order z reading
	mov	@r1,a		;save hi order reading
	inc	r0
	inc	r1
	mov	a,@r0		;get lo order reading
	mov	@r1,a		;save lo order reading

	inc	r0
	inc	r1
	mov	a,@r0		;get hi order w reading
	mov	@r1,a		;save hi order reading
	inc	r0
	inc	r1
	mov	a,@r0		;get lo order reading
	mov	@r1,a		;save lo order reading

	inc	r0
	inc	r1
	mov	a,@r0		;get hi order t reading
	mov	@r1,a		;save hi order reading
	inc	r0
	inc	r1
	mov	a,@r0		;get lo order reading
	mov	@r1,a		;save lo order reading
	ret

;a = chan # (0 to 3)
;return with jog and jdir set according to value of selected analog chan
jscheck:
	rl	a
	inc	a
	mov	r2,a
	clr	jog
	clr	jdir
	add	a,#xj
	mov	r0,a		;r0 points to lsb of chan rdg
	mov	a,#xb
	add	a,r2
	mov	r1,a		;r1 points to lsb of chan base
	clr	c
	CRON
	mov	a,@r0
	subb	a,@r1
	dec	r0
	dec	r1
	mov	b,a		;b = lsb of difference
	mov	a,@r0
	CROF
	subb	a,@r1
	jb	acc.7,js1	;jmp if a.b is negative
	;a.b is positive
	clr	c
	xch	a,b
	subb	a,dband+1
	xch	a,b
	subb	a,dband		;a.b = val - dband
	jb	acc.7,jsret
	setb	jog
	jmp	jsret
js1:	;a.b is negative
	xch	a,b
	add	a,dband+1
	xch	a,b
	addc	a,dband		;a.b = val + dband
	jnb	acc.7,jsret
	setb	jog
	setb	jdir		;reverse signs
jsret:	ret

zskip:
sk00:
	clr	a
	movc	a,@a+dptr
	jnz	sk01
	jmp	sk02
sk01:	inc	dptr
	jmp	sk00
sk02:	inc	dptr
	inc	r6
	ret

;search for match between char string in cmdbuf and cmdtbl. length of string is in r3.
ismatch:
	mov	r6,#0	;command position counter
	mov	dptr,#cmdtbl
im00:
	mov	r0,#cmdbuf
	mov	a,r3	;string length
	mov	r5,a
im03:
	clr	a
	movc	a,@a+dptr
	jnz	im04
	inc	dptr
	inc	r6
	jmp	im05
im04:
	clr	c
	subb	a,@r0
	jnz	im01
	;chars match
	djnz	r5,im02
	jmp	match
im02:
	inc	r0
	inc	dptr
	jmp	im03
im01:
	call	zskip
im05:
	movc	a,@a+dptr
	jnz	im00
	;end of command table
nomatch:
        clr	a
;        call	cmd_init
        jmp	imrt
match:
	inc	dptr
	clr	a
	movc	a,@a+dptr
	jnz	nomatch
        REFRESH              ; refresh watchdog timer
	;2*r6 is offset into jmptbl:
	mov	a,r6
	add	a,r6
	mov	r0,a
	mov	dptr,#jmptbl
	movc	a,@a+dptr       ;high byte of addrs
	mov	r1,a
	mov	a,r0
	inc	a
	movc	a,@a+dptr       ;low byte of address
	mov	cptrl,a
	MOV	cptrh,r1
;	setb	cmd_rdy
	mov	dpl,a
	mov	dph,r1
	clr	a
	jmp	@a+dptr		;jump to command procedure
imrt:
	ret

;initialize command decoder (register bank 2)
cmd_init:
	mov	r3,#0	;command char count
	clr	numok
	clr	cmdrcvd
	clr	cmderr
	clr	cmd_rdy
	mov	cbufptr,#cmdbuf
	mov	rxptr,#rxbuf	;UART receive buffer
	mov	r0,#cparam
	mov	r1,#MSIZ
z00:	mov	@r0,#0
	inc	r0
	djnz	r1,z00
	ret

;a = received char
process_char:
	;decide what to do with char:
	cjne	a,#0dh,pcctnu
	jmp	eocmd
eocmd:  ;end of line
	clr	a
	jb	cmdrcvd,excmd	;jmp if command entered
	cjne	r3,#0,excmd	;in case command does not need parameter
	jmp 	pcfin           ;extra end of line: ignore
        jb	cmderr,pcq
excmd:	call	ismatch		;this will set up cptrh.cptrl
;if a = 0: bad command. a = 1: good command
pcq:
	jnz	pcb
	mov	A,#'0'         ;BAD
	jmp	pcp
pcb:	cjne	a,#2,pcg
    	jmp	pcig
pcg:	MOV     A,#'1'		;GOOD
;	CPL	DBUG_LED
	MOV	UTMOUT,#UCOUNT	;RESET UART TIMEOUT COUNT
pcp:    CALL    SENDCHAR
	MOV	DPTR,#SEPARATOR
	CALL	SENDSTRING
pcig:	call	cmd_init
	jmp	pcfin
pcctnu:
	jb	cmdrcvd,pc01	;jump if command has been received
	;complete command not received yet
	;delimiter?
	cjne	a,#' ',pc001
	jmp	isdelim
pc001:	cjne	a,#',',pc002
	jmp	isdelim
pc002:	cjne	a,#'=',pc003
	jmp	isdelim
pc003:	cjne	a,#09h,pc004    ;tab
isdelim:
	cjne	r3,#0,pc005
	jmp	numerr		;no command has been entered
pc005:	setb	cmdrcvd         ;mark command as being received
	jmp	pcfin
pc004:
	;must be alphabetic:
	;upper case:
ucck:	JALT	'A',numerr
	JAGT	'Z',cklc
	;upper case. convert to lower case
	orl	a,#020h
cklc:	JALT	'a',numerr
	JAGT	'z',numerr
	;alphabetic char. put in buffer
	mov	r0,cbufptr
	cjne	r0,#cmdbuf+CMDSIZ,pc00  ;jmp if buffer not full
	;buffer full
	jmp	numerr
pc00:	mov	@r0,a
	inc	r3	;increment char count
	inc	r0
	mov	cbufptr,r0
	jmp pcfin
pc01:
	;must be a number
	JNB	USEHEX,PC01A
	;HEX
	CALL	ASCII2HEX
	JC	numerr
	JMP	PC01B
PC01A:
	JALT	'0',numerr
	JAGT	'9',numerr
PC01B:
	;char is numeric
	anl	a,#0fh
	setb	numok		;set the numeric bit
	;decimal to hex conversion:
	push	acc
	JB	USEHEX,PC01C
	FACX10	cparam+MSIZ-1,cparamb+MSIZ-1		;multiply cparam by 10
	JMP	PC01D
PC01C:	MOV	R1,#CPARAM
	CALL	MMUL16			;MULTIPLY CPARAM BY 16
PC01D:
	;add digit to cparam:
	mov	r0,#cparam+MSIZ-1
	mov	r1,#MSIZ
	pop	acc
	clr	c
pc02:	addc	a,@r0
	mov	@r0,a
	clr	a
	dec	r0
	djnz	r1,pc02
        jmp	pcfin
numerr:
	setb	cmderr
pcfin:
	ret

process_buf:
	mov	rxptr,#rxbuf
pb1:
	mov	r0,rxptr
	mov	a,@r0
	cjne	a,#0dh,pb2	;jmp if char is not cr
	;char is cr: end of command
	call	process_char
	ret
pb2:
	call	process_char
	inc	rxptr
	jmp	pb1
;end of process_buf

OUTNUM:
	JB	USEHEX,PNTHEX
	CALL	OUT5
	RET
PNTHEX:	CALL	OUT4H
	RET

;COMMANDS
;a = 0 at start
;return with a=0 if error, a=1 if ok and '>' response wanted, a=2 if ok and no '>'.

; COMMAND 0 - switches
switches:
	;PUT PAD INTO WRD AND PRINT WRD. (OUT5 MODIFIES WRD)
	MOV	WRD,PAD
	MOV	WRD+1,PAD+1
	;add id bit:
	anl	wrd,#0fh
	orl	wrd,#80h	;ID
	JNB	DOG_RST,$+6	;SKIP IF WATCHDOG HAS NOT TIMED OUT
      	ORL	WRD,#10H	;ADD WATCHDOG RESET BIT
	MOV	R1,#WRD
	CALL	OUTNUM
	MOV	DPTR,#SEPARATOR
	CALL	SENDSTRING
	jnb	numok,SWI0
	CLR	DOG_RST		;CLEAR WATCHDOG RESET BIT IF PARAM INCLUDED WITH THIS CMD.
SWI0:
	mov	a,#2
	ret

; COMMAND 6 - leds
leds:
	MOV	WRD,LED
	MOV	WRD+1,LED+1
	;add id bit:
	anl	wrd,#0fh
	orl	wrd,#40h
	;add jog bit:
	JNB	JOGOK,LEDS1 	;JMP IF NOT JOGGING
      	ORL	WRD,#10H	;ADD JOGGING BIT
LEDS1:
      	;REMOVE JOG SPEED BITS:
      	ANL	WRD+1,#0E1H
	JNB	DOG_RST,$+6	;SKIP IF WATCHDOG HAS NOT TIMED OUT
      	ORL	WRD+1,#2H	;ADD WATCHDOG RESET BIT
	MOV	R1,#WRD
	CALL	OUTNUM
	MOV	DPTR,#SEPARATOR
	CALL	SENDSTRING
	jnb	numok,LEDS2
	CLR	DOG_RST		;CLEAR WATCHDOG RESET BIT IF PARAM INCLUDED WITH THIS CMD.
LEDS2:
	mov	a,#2
	ret

; COMMAND 13
JOGINFO:
;	MOV	WRD,JOGH
	MOV	A,PAD+1
	MOV	C,ACC.7		;JOG ENABLE SWITCH BIT
	MOV	A,LED+1
	RR	A               ;JOG SPEED BITS IN A0 TO A3
	MOV	ACC.4,C
	MOV	WRD,A
	MOV	WRD+1,JOGH+1
	;add id bit:
	anl	wrd,#01Fh
	orl	wrd,#20h
	MOV	R1,#WRD
	CALL	OUTNUM
	MOV	DPTR,#SEPARATOR
	CALL	SENDSTRING
	mov	a,#2
	ret

; COMMAND 1
joysticks:
	jnb	numok,jbd
	mov	a,cparam+1      ;switch number
	;a=chan number: 0 to 4
	cjne	a,#5,$+3
	jnc	frpot	;jmp if a >= 5
	;interchange w and z axes:
	jnb	acc.1,joy2
     	cpl	acc.0
     	jmp	joy2
frpot:
	mov	r0,#fr	;r0 points to feedrate reading
	mov	a,@r0
	mov	wrd,a
	inc	r0
	mov	a,@r0
	mov	wrd+1,a
	jmp	joy1
joy2:
	rl	a
	inc	a	;a = offset into lsb
	mov	b,a
	add	a,#xj
	mov	r0,a    ;r0 points to reading
	mov	a,#xb
	add	a,b
	mov	r1,a    ;r1 points to base
	;reading - base
	mov	a,@r0
	clr	c
	subb	a,@r1
	mov	wrd+1,a
	dec	r0
	dec	r1
	mov	a,@r0
	subb	a,@r1
	mov	wrd,a
	jnb	acc.7,joy1
	mov	a,#'-'
	call	SENDCHAR
	mov	a,wrd+1
	cpl	a
	setb	c
	addc	a,#0
	mov	wrd+1,a
	mov	a,wrd
	cpl	a
	addc	a,#0
	mov	wrd,a
joy1:	mov	r1,#wrd
	call	outnum
	mov	dptr,#separator
	call	sendstring
	mov	a,#2
	jmp	jok
jbd:	clr	a
jok:
	ret

; COMMAND 2
setaddress:
	jnb	numok,sabd
	mov	display_adr,cparam
	mov	display_adr+1,cparam+1
	mov	a,#1
	jmp	saok
sabd:
	clr	a
saok:
	ret

; COMMAND 3
readaddress:
	mov	R7,display_adr
	mov	R6,display_adr+1
	CALL	CAP_RCV
	;RESULT IN R5.R4
	MOV	WRD,R5
	MOV	WRD+1,R4
	MOV	R1,#WRD
	CALL	OUTNUM
	MOV	DPTR,#SEPARATOR
	CALL	SENDSTRING
	mov	a,#2
	ret

; COMMAND 4
writeaddress:
	jnb	numok,wabd
	mov	R5,cparam
	mov	R4,cparam+1
	mov	R7,display_adr
	mov	R6,display_adr+1
	call	CAP_SEND16
	mov	a,#1
	jmp	waok
wabd:
	clr	a
waok:
	ret

; COMMAND 9
led_current:
	jnb	numok,lcbd
	mov	a,cparam+1
	anl	a,#0fh
	mov	ledi,a
	mov	ledcs,#0
	call	led_config
	inc	ledcs
	call	led_config
	mov	a,#1
	jmp	lcok
lcbd:	clr	a
lcok:	ret

; COMMAND 11
hexordec:
	jnb	numok,hdbd
	mov	a,cparam+1
	jz	hdd
	setb	usehex
	jmp	hdd1
hdd:	clr	usehex
hdd1:	mov	a,#1
	jmp	hdok
hdbd:	clr	a
hdok:	ret

; COMMAND 10
set_type:
	jnb	numok,stbd
	mov	a,cparam        ;switch number
	;a=switch number: 0 to 11
	cjne	a,#12,$+3
	jnc	stbd	;jmp if a >= 12
	add	a,#type ;address of selected switch type
	mov	r0,a
	mov	@r0,cparam+1    ;switch type
	mov	a,#1
	jmp	stok
stbd:	clr	a
stok:	ret 

; COMMAND 7
blon:
	jnb	numok,blonbd
	mov	a,cparam+1
	;should be 0 to 11
	cjne	a,#12,b1
	jmp	blonbd
b1:	jnc	blonbd
	;A < 12
	INC	A
	MOV	R6,#0  	;mask hi
	MOV	R7,#1	;mask lo
	MOV	B,A
B2:	DJNZ	B,B3
	MOV	A,R6
	ORL	LEDCON,A
	ORL	LEDCOF,A
	MOV	A,R7
	ORL	LEDCON+1,A
	ORL	LEDCOF+1,A
	MOV	A,#1
	JMP	BLONOK
B3:	CLR	C       ;shift mask left
	MOV	A,R7
	RLC	A
	MOV	R7,A
	MOV	A,R6
	RLC	A
	MOV	R6,A
	JMP	B2
blonbd:	clr	a
blonok:	ret

; COMMAND 8
bloff:
	jnb	numok,bloffbd
	mov	a,cparam+1
	;should be 0 to 11
	cjne	a,#12,c1
	jmp	bloffbd
c1:	jnc	bloffbd
	;a < 12
	INC	A
	MOV	R6,#0FFH
	MOV	R7,#0FEH
	MOV	B,A
C2:	DJNZ	B,C3
	MOV	A,R6
	ANL	LEDCOF,A
	ANL	LEDCON,A
	MOV	A,R7
	ANL	LEDCOF+1,A
	ANL	LEDCON+1,A
	MOV	A,#1
	JMP	BLOFFOK
C3:	SETB	C
	MOV	A,R7
	RLC	A
	MOV	R7,A
	MOV	A,R6
	RLC	A
	MOV	R6,A
	JMP	C2
bloffbd:	clr	a
bloffok:	ret

; COMMAND 5 - load default settings into flash
flash_reload:
	CLR	EA	;NO INTERRUPTS WHEN READING OR WRITING FLASH (841 ANOMALY)
        call	iload
        SETB	EA
	MOV	DPTR,#SEPARATOR
	CALL	SENDSTRING
	mov	a,#1
	ret

; COMMAND 15
save_from_chip:
	clr	ea
	call	iload_fc
	setb	ea
	MOV	DPTR,#SEPARATOR
	CALL	SENDSTRING
	mov	a,#1
	ret

; COMMAND 12 - SET JOYSTICK BASE REGISTERS TO CURRENT VALUES OF  STICK READINGS, AND SET JOYSTICK DEADBAND.
set_adc_base:
	jnb	numok,noprm	;jmp if no deadband param was entered
	mov	dband,cparam
	mov	dband+1,cparam+1
noprm:	call	setbase
	mov	a,#1
	ret

; COMMADN 14
wdog_test:
	SETB	WDWR
	MOV	WDCON,#82H	;IMMEDIATE RESET
	jmp	$       ;WAIT HERE UNTIL WATCHDOG TIMER RESETS COMPUTER
	ret

; COMMAND 16 - RETURN VERSION
version:
	MOV	WRD,#VERMAJ
	MOV	WRD+1,#VERMIN
	MOV	R1,#WRD
	CALL	OUTNUM
	MOV	DPTR,#SEPARATOR
	CALL	SENDSTRING
	mov	a,#2
	ret

; COMMAND 17 - return the capacitance chip type:
qchip:
	jnb	NOCHIP,qid
	;cap chip was not identified
	;return 1234
	MOV	WRD,#04H
	MOV	WRD+1,#0D2H
	jmp	qc1
qid:	jb	SPIF,is_spi
	;chip is I2C: AD7142-1
	;return 7143
	MOV	WRD,#1BH
	MOV	WRD+1,#0E7H
	jmp	qc1
is_spi:
	;chip is SPI: AD7142
	;return 7142
	MOV	WRD,#1BH
	MOV	WRD+1,#0E6H
qc1:	MOV	R1,#WRD
	CALL	OUTNUM
	MOV	DPTR,#SEPARATOR
	CALL	SENDSTRING
	mov	a,#2
	ret


uart_test:
	;Send UART test string:
	MOV	WRD,#0d4h
	MOV	WRD+1,#031h	;54321
	MOV	R1,#WRD
	CALL	OUTNUM
	MOV	DPTR,#SEPARATOR
	CALL	SENDSTRING
	ret

CMDTBL:
		db	's',0        	;0
		db	'j',0		;1
		db	'a',0		;2
		db	'r',0		;3
		db	'w',0		;4
		db	'reload',0	;5
		DB	'l',0		;6
		db	'o',0		;7
		db	'f',0		;8
		db	'i',0		;9
		db	'type',0	;10
		db	'h',0		;11
		db	'b',0		;12
		db	'q',0		;13
		db	'dog',0		;14
		db	'save',0	;15
		db	'version',0	;16
		db	'qchip',0	;17
		db	0  		;end of CMDTBL

JMPTBL:
		dw	switches            	;0
		dw	joysticks   		;1
		dw	setaddress		;2
		dw	readaddress 		;3
		dw	writeaddress		;4
		dw	flash_reload		;5
		dw	leds			;6
		dw	blon			;7
		dw	bloff			;8
		dw	led_current		;9
		dw	set_type		;10
		dw	hexordec		;11
		dw	set_adc_base		;12
		dw	joginfo			;13
		dw	wdog_test		;14
		dw	save_from_chip		;15
		dw	version			;16
		dw	qchip			;17
;end of JMPTBL

END

