DEBUG EQU 0
;;SPIF EQU 0

VERMAJ EQU	1
VERMIN EQU	10

MSIZ	EQU	2
CMDSIZ	EQU	20	;size of command buffer
RXBUFSIZ	EQU	20
TICKVAL	EQU	8	;TICK INTERVAL IN MS./5  (40 MS.)
PONWT	EQU	75	;POWER ON WAIT IN TICKS
UCOUNT	EQU	25	;UART TIMEOUT COUNT (TIME = UCOUNT * TICKVAL)

SPI_CLK EQU 	P3.5
SPI_OUT	EQU	P3.4
SPI_IN	EQU	P3.3
LEDCS1	EQU	P2.5
LEDCS2	EQU	P2.3
CAPCS	EQU	P2.4
DBUG_LED       EQU     P2.1
CLICK	EQU	P2.2
CHIPINT	EQU	P3.2
DOG_RST EQU	P2.0
BINCOM	EQU	P2.6
FINIT	EQU	P2.7

;FOR I2C VERSION OF CAP CHIP (AD7142-1):
SDA	EQU	P3.3
ADD0	EQU	P3.4
ADD1	EQU	P2.4
SCLK	EQU	P3.5

TESTOUT EQU	P3.7


;SHIFT A BYTE LEFT
SHBL	MACRO	BNAM
	MOV	A,BNAM
	RLC	A
	MOV	BNAM,A
	ENDM

;SHIFT A BYTE RIGHT
SHBR	MACRO	BNAM
	MOV	A,BNAM
	RRC	A
	MOV	BNAM,A
	ENDM

;SHIFT BYTE STRING LEFT. CLEAR C BEFORE CALLING.REG IS LEAST SIG BYTE, NBR IS NUMBER OF BYTES.
SBSL	MACRO  REG,	NBR
	SHBL	REG
	IF (NBR > 1)
	 SBSL REG-1,NBR-1
	ENDIF
	ENDM

;SHIFT BYTE STRING RIGHT. CLEAR C BEFORE CALLING.REG IS MOST SIG BYTE, NBR IS NUMBER OF BYTES.
SBSR	MACRO  REG,	NBR
	SHBR	REG
	IF (NBR > 1)
	 SBSR REG+1,NBR-1
	ENDIF
	ENDM

;SHIFT FAC1 MANTISSA LIFT 1 BIT (MULTIPLY BY 2)
FACX2	MACRO   FAC1
	CLR	C
	SBSL	FAC1,MSIZ
	ENDM

;ADD TWO BYTES PLUS CARRY. BYTEA + BYTEB -> BYTEA
PADD	MACRO	BYTEA,BYTEB
	MOV	A,BYTEA
	ADDC	A,BYTEB
	MOV	BYTEA,A
	ENDM

;ADD COMPLEMENT OF BYTE AND CARRY
ADCPL	MACRO	BYTEA
	MOV	A,BYTEA
	CPL	A
	ADDC	A,#0
	MOV	BYTEA,A
	ENDM

;ADD COMPLEMENT OF BYTE AT R1 AND CARRY
ADCPLR1	MACRO
	MOV	A,@R1
	CPL	A
	ADDC	A,#0
	MOV	@R1,A
	DEC	R1
	ENDM

;ADD COMPLEMENT OF BYTE STRING A TO CARRY. RESULT IN BYTE STRING A
;NBR IS NUMBER OF BYTES IN STRING. BSTA IS LEAST SIG. BYTE.
BSCPL	MACRO	BSTA,NBR
	ADCPL	BSTA
	IF (NBR > 1)
	 BSCPL BSTA-1,NBR-1
	ENDIF
	ENDM

;ADD COMPLEMENT OF BYTE STRING @R1 TO CARRY. RESULT IN BYTE STRING @R1
;NBR IS NUMBER OF BYTES IN STRING. @R1 IS LEAST SIG. BYTE.
BSCPLR1	MACRO	NBR
	ADCPLR1
	IF (NBR > 1)
	 BSCPLR1 NBR-1
	ENDIF
	ENDM

;ADD BYTE STRING A TO BYTE STRING B. RESULT IN BYTE STRING A
;NBR IS NUMBER OF BYTES IN STRING. BSTA, BSTB ARE LEAST SIG. BYTES. CLEAR C BEFORE USING
BSADD	MACRO	BSTA,BSTB,NBR
	PADD	BSTA,BSTB
	IF (NBR > 1)
	 BSADD BSTA-1,BSTB-1,NBR-1
	ENDIF
	ENDM

;SHIFT BYTE STRING LEFT. CLEAR C BEFORE CALLING.REGA,REGB IS LEAST SIG BYTE, NBR IS NUMBER OF BYTES.
;REGA IS SHIFTED STRING, REGB RECEIVES RESULT ALSO
SBSLB	MACRO  REGA,REGB,NBR
	SHBL	REGA
	MOV	REGB,A
	IF (NBR > 1)
	 SBSLB REGA-1,REGB-1,NBR-1
	ENDIF
	ENDM

;SHIFT FAC1 MANTISSA LIFT 1 BIT AND PUT IN FAC2.
FACX2B	MACRO   FAC1,FAC2
	CLR	C
	SBSLB	FAC1,FAC2,MSIZ
	ENDM

;ADD FAC2 MANTISSA TO FAC1 MANTISSA
ADDAB	MACRO   FAC1,FAC2
	CLR	C
	BSADD	FAC1,FAC2,MSIZ
	ENDM



;MULTIPLY FAC1 MANTISSA BY 10 (DECIMAL)
; FAC2 IS USED FOR TEMPORARY STORAGE
FACX10	MACRO   FAC1,FAC2
	FACX2B  FAC1,FAC2
	FACX2   FAC1
	FACX2   FAC1
	ADDAB   FAC1,FAC2
	ENDM

;REPLACE VA WITH VA + VB. LEAVE RESULT IN FAC
FADDS	MACRO	VA,VB
	MOV	R0,#VA
	CALL	GETA
	MOV	R0,#VB
	CALL	GETB
	CALL	FADDAB
	MOV	R0,#VA
	CALL SAVEFACR0
	ENDM

;REPLACE VA WITH VA - VB. LEAVE RESULT IN FAC
FSUBS	MACRO	VA,VB
	MOV	R0,#VA
	CALL	GETA
	MOV	R0,#VB
	CALL	GETB
	XRL	FACB,#1
	CALL	FADDAB
	MOV	R0,#VA
	CALL SAVEFACR0
	ENDM

;FAC <- VA + VB.
FADD	MACRO	VA,VB
	MOV	R0,#VA
	CALL	GETA
	MOV	R0,#VB
	CALL	GETB
	CALL	FADDAB
	ENDM

;FAC <- VA - VB.
FSUB	MACRO	VA,VB
	MOV	R0,#VA
	CALL	GETA
	MOV	R0,#VB
	CALL	GETB
	XRL	FACB,#1
	CALL	FADDAB
	ENDM

;FAC <- FAC + VB.
FADDF	MACRO	VB
	MOV	R0,#VB
	CALL	GETB
	CALL	FADDAB
	ENDM

;FAC <- FAC - VB.
FSUBF	MACRO	VB
	MOV	R0,#VB
	CALL	GETB
	XRL	FACB,#1
	CALL	FADDAB
	ENDM

;FAC <- FAC - (DPTR).
FSUBFEX	MACRO
	CALL	GETBEX
	XRL	FACB,#1
	CALL	FADDAB
	ENDM

;SHIFT BYTE @R0 LEFT 4 BITS. SHIFT IN BITS 0-3 OF B
SHL4S	MACRO
	MOV	A,@R0
	SWAP	A
	PUSH	ACC
	ANL	A,#0F0H
	ORL	A,B
	MOV	@R0,A
	POP	ACC
	ANL	A,#0FH
	MOV	B,A
	DEC	R0
	ENDM

;SHIFT BYTE @R0 LEFT 4 BITS. SHIFT IN BITS 0-3 OF B.LAST STEP
SHL4L	MACRO
	MOV	A,@R0
	SWAP	A
	ANL	A,#0F0H
	ORL	A,B
	MOV	@R0,A
	ENDM

;SHIFT MANTISSA LEFT 4 BITS.SHIFT IN B[3..0],R0 POINTS TO LEAST SIG. BYTE.
;NBR IS SIZE OF MANTISSA.
SHLMANT4	MACRO	NBR
	IF	(NBR > 1)
		SHL4S
	ELSE
		SHL4L
	ENDIF
	IF	(NBR >  1)
		SHLMANT4	NBR-1
	ENDIF
	ENDM

;SHIFT MANTISSA AT R0 LEFT 4 BITS. ADRS IS ADDRESS OF MOST SIG BYTE OF MANTISSA.
;A[3..0] IS SHIFTED INTO THE LOW ORDER BYTE.
SHLMANTA	MACRO
	ANL	A,#0FH
	MOV	B,A
	SHLMANT4	MSIZ
	ENDM

;JUMP TO ADRS IF A IS LESS THAN VAL:
JALT	MACRO	VAL,ADRS
	CJNE	A,#VAL,$+5
	SJMP	$+7
	JNC	$+5
	LJMP	ADRS
	ENDM

;JUMP TO ADRS IF A IS GREATER THAN VAL:
JAGT	MACRO	VAL,ADRS
	CJNE	A,#VAL,$+5
	SJMP	$+7
	JC	$+5
	LJMP	ADRS
	ENDM

;MOVE BYTES FROM @R1 TO @R2
FMOV1	MACRO	NBR
	MOV	A,@R1
	MOV	@R0,A
	IF	(NBR > 1)
		INC	R0
		INC	R1
		FMOV1	NBR-1
	ENDIF
	ENDM

;MOVE FLOAT VB TO VA
FMOV	MACRO	VA,VB
	MOV	R0,#VA
	MOV	R1,#VB
	FMOV1	FSIZ
	ENDM

INCEAD	MACRO
	inc	eadrl
	mov	a,eadrl
	jnz	$+4
	inc	eadrh
	ENDM

;SAVE 4 BYTES (1 PAGE) IN FLASH, INCREMENT PAGE ADDRESS:
SAV4	MACRO	NUM1,NUM2
	MOV	EDATA1,#LOW(NUM1)
	MOV	EDATA2,#HIGH(NUM1)
	MOV	EDATA3,#LOW(NUM2)
	MOV	EDATA4,#HIGH(NUM2)
	MOV	ECON,#5
	MOV	ECON,#2
	INCEAD
	ENDM

;GET 4 BYTES FROM FLASH, INCREMENT PAGE ADDRESS:
GET4	MACRO
	MOV	ECON,#1
	INCEAD
	ENDM



;SPI CLOCK HIGH OR LOW TIME = 8 + 3N CYCLES
;12.6 MHZ CLOCK: 2.9 MICROSECS IF N = 10
SPIWAIT	MACRO
;	NOP
;	PUSH	B
;	MOV	B,#1
;	DJNZ	B,$
;	POP	B
	NOP
	PUSH	B       ;OK WITHOUT THE PUSH & POP TOO
	POP	B
	NOP
	ENDM

INCR7R6	MACRO
	INC	R6
	CJNE	R6,#0,$+4
	INC	R7
	ENDM

;CRITICAL REGION ON:
CRON	MACRO
	CLR	EA
	ENDM

;CRITICAL REGION OFF:
CROF	MACRO
	JNB	INTON,$+5
	SETB	EA
	ENDM

;REFRESH WATCHDOG TIMER
REFRESH	MACRO
        CLR     EA              ; refresh watchdog timer
	SETB    WDWR
	SETB    WDE
	SETB    EA
	ENDM

BSEG
ORG 0
numok:		dbit	1
cmdrcvd:	dbit	1
cmderr:		dbit	1


SPIRDY:		DBIT	1
tick:		dbit	1
TPAD:		DBIT	1
cmd_rdy:	dbit	1
usehex:		dbit	1
jog:		dbit	1
jdir:		dbit	1
baseloaded:	dbit	1
JOGOK:		DBIT	1
POWERRDY:	DBIT	1
INTON:		DBIT	1
SPIF:		DBIT	1	;I2C/SPI FLAG
NOCHIP:		DBIT	1	;WILL BE SET IF CAP CHIP WAS NOT IDENTIFIED

DSEG
ORG 30h
cbufptr:	ds	1	;command buffer pointer
cparam:		ds	MSIZ	;command parameter
cparamb:       	ds	MSIZ
display_adr:	ds	MSIZ
tickcount:	ds	1
LEDCS:		DS	1
cptrh:		ds	1
cptrl:		ds	1
PAD:		DS	2	;LAST TOUCH READING
LED:		DS	2	;LED STATUS
LEDT:		DS	2	;WORKING LED STATUS
TYPE:		DS	12	;SWITCH DEFINITIONS
MASK:		DS	2
OFFON:		DS	2
ONOFF:		DS	2
LEDI:		DS	1	;LED CURRENT (0 TO 15)
WRD:		DS	2
rxptr:		ds	1
dband:		ds	2	;joystick deadband
basecount:	ds	1
JOGH:		ds	2
PONCOUNT:	DS	1	;POWER ON COUNT
UTMOUT:		DS	1	;UART TIMEOUT COUNTER
LEDCON:		DS	2
LEDCOF:		DS	2
CMDNBR:		DS	1
BYTECOUNT:	DS	1

ISEG
ORG 080h
cmdbuf:		ds	20      ;command buffer
outbuf:		ds	10
rxbuf:		ds	RXBUFSIZ


xj:		ds	2	;x joystick reading
yj:		ds	2
wj:		ds	2
zj:		ds	2
tj:		ds	2	;5th axis
		ds	4	;unused chans
fr:		ds	2	;feedrate pot rdg.
xb:		ds	2	;x base
yb:		ds	2
wb:		ds	2
zb:		ds	2
tb:		ds	2

stack:

XSEG
ORG 100h
;stepbase:	ds	MAXSTEPS*STEPSIZE
 